### PR TITLE
Fix `regi2c_*` functions for `esp32h2`

### LINKED ISSUE #1736: Wrong `regi2c_*` functions in `esp32h2` clocks.

### PR DESCRIPTION
**Pull request by playfulFence**
closes #1736 

### Submission Checklist 📝
- [x] I have updated existing examples or added new ones (if applicable).
- [x] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [x] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [x] My changes are in accordance to the [esp-rs API guidelines](https://github.com/esp-rs/esp-hal/blob/main/API-GUIDELINES.md)

#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/CONTRIBUTING.md) and followed its instructions.

#### Description
I noticed a change in the corresponding functionality in esp-idf:  https://github.com/espressif/esp-idf/blob/master/components/esp_rom/patches/esp_rom_regi2c_esp32h2.c

### CODE REVIEW

File: esp-hal/src/clock/clocks_ll/esp32h2.rs [hunk 1]
```diff
@@ -239,54 +234,49 @@ fn clk_ll_bus_update() {
...
-    }
+    modem_lpcon
+        .clk_conf()
+        .modify(|_, w| w.clk_i2c_mst_en().set_bit());
 
     // Before config I2C register, enable corresponding slave.
     match block {
-        REGI2C_BBPLL => {
-            reg_set_bit(I2C_MST_ANA_CONF2_REG, REGI2C_BBPLL_DEVICE_EN);
+        v if v == REGI2C_BBPLL => {
```
Comment (bjoernQ) [inline esp-hal/src/clock/clocks_ll/esp32h2.rs:245]: I wonder if we should have this the preferred style to match constants 🤔 - if yes, we should have that documented somewhere (don't see a fitting document currently for code-style)

But we are also not consistent across the current code base, I think

**Review by bjoernQ — APPROVED** [review]
LGTM - we should discuss the match-constants pattern (independent of this PR)

**Review by SergioGasquez — APPROVED** [review]
LGTM! Thanks
