### PR TITLE
I2c: attempt empty writes

### LINKED ISSUE #2504: I2C doesn't error correctly on empty transfers
## Bug description

Sending an empty write to a non-existent device unexpectedly returns Ok.
This should fail with an Ack error.
This wasn't always the case, it used to fail correctly.

Empty writes are important for Ack-polling eeproms and checking for device existence (probing).

## To Reproduce

```Rust
let mut i2c = I2c::new(peripherals.I2C0, io.pins.gpio4, io.pins.gpio5, 100.kHz());

let result0 = i2c.write(0x1C, &[]);
let result1 = i2c.write(0x1C, &[0]);

println!("Empty transfer result {:?}", result0);
println!("1-byte transfer result {:?}", result1);
```

```
Empty transfer result Ok(())
1-byte transfer result Err(AckCheckFailed)
```

## Expected behavior

```
Empty transfer result Err(AckCheckFailed)
1-byte transfer result Err(AckCheckFailed)
```

## Environment

- Target device: ESP32-S3
- Crate name and version: esp-hal 6d6f6a7baa954ed984bdcc433b215a579954c8b6 (`main` as of writing)

### PR DESCRIPTION
**Pull request by bugadani**
## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [x] I have updated existing examples or added new ones (if applicable).
- [x] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [x] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [x] I have added necessary changes to user code to the [Migration Guide](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/MIGRATING-0.21.md).
- [x] My changes are in accordance to the [esp-rs API guidelines](https://github.com/esp-rs/esp-hal/blob/main/documentation/API-GUIDELINES.md)

#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/documentation/CONTRIBUTING.md) and followed its instructions.

#### Description

Closes #2504

### CODE REVIEW

File: hil-test/tests/i2c.rs [hunk 1]
```diff
@@ -44,6 +44,13 @@ mod tests {
         Context { i2c }
     }
 
+    #[test]
+    #[timeout(3)]
+    fn empty_write_returns_ack_error_for_unknown_address(mut ctx: Context) {
+        assert_eq!(ctx.i2c.write(0xab, &[]), Err(Error::AckCheckFailed));
+        assert_eq!(ctx.i2c.write(0x77, &[]), Ok(()));
```
Comment (Dominaezzz) [inline hil-test/tests/i2c.rs:51]: At first I read this thinking, shouldn't this fail too? But 0x77 is the real device connected to the HIL device. Perhaps 0x77 should go behind a const or an extra comment should go here for clarity.

**Review by Dominaezzz — APPROVED** [review]

**Review by bjoernQ — APPROVED** [review]
