### PR TITLE
Fix eh0.2 `set_high`/`set_low`

### LINKED ISSUE #2263: Something broke in f11c18a6b93eb54e02494fa4df2a2941dcd5b44f
Commit f11c18a6b93eb54e02494fa4df2a2941dcd5b44f broke something

Here is the repro: https://github.com/bjoernQ/rust-esp32s3-ili9341/blob/borked/

The commit before works

### PR DESCRIPTION
**Pull request by bjoernQ**
## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [ ] I have updated existing examples or added new ones (if applicable).
- [x] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [ ] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [ ] I have added necessary changes to user code to the [Migration Guide](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/MIGRATING-0.21.md).
- [x] My changes are in accordance to the [esp-rs API guidelines](https://github.com/esp-rs/esp-hal/blob/main/documentation/API-GUIDELINES.md)

#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/documentation/CONTRIBUTING.md) and followed its instructions.

#### Description
Fixes #2263 

No CHANGELOG entry since this just fixes something introduced in the current development cycle

#### Testing
see linked issue, added HIL tests

### CODE REVIEW

File: esp-hal/src/gpio/mod.rs [hunk 1]
```diff
@@ -2601,11 +2601,11 @@ mod embedded_hal_02_impls {
         type Error = core::convert::Infallible;
 
         fn set_high(&mut self) -> Result<(), Self::Error> {
-            self.pin.is_set_high();
+            self.pin.set_high();
```
Comment (bugadani) [inline esp-hal/src/gpio/mod.rs:2604]: 🤣🤦‍♂️

**Review by bugadani — APPROVED** [review]
Thank you.

**Review by SergioGasquez — APPROVED** [review]
LGTM! Nice catch hahah
