### PR TITLE
Fix LEDC divider calculation, use REF_TICK when needed

### LINKED ISSUE #135: LEDC produces the wrong frequency
The current implementation of LEDC produces the wrong frequency which can be measured by a logic analyzer or by using a piezo buzzer.

I'm having the bug on the ESP32-S3 platform.
## Example of the issue
By using the same example as provided here: [esp32s3-hal/examples/ledc.rs](https://github.com/esp-rs/esp-hal/blob/main/esp32s3-hal/examples/ledc.rs), the code is supposed to produce a frequency of 24 kHz with a duty of 10%. If we put a logic analyzer on the output pins, we get a frequency of around 300Hz, with a duty of 10%.
image

## Expected result
The frequency emitted on the GPIO should represent the frequency used in the software.

## Additional info
I've attached a capture of the frequency, which can be opened in Saleae logic 2, for a deeper analysis
[ledc-bug-log.tar.gz](https://github.com/esp-rs/esp-hal/files/9278634/ledc-bug-log.tar.gz)
 
I've also noticed that there are constant irregularities in the frequency emitted, sometimes it goes a little bit over, or a little bit under, and this is constant along the whole capture.

The bug is present with any frequency, duty and bit resolution.

### PR DESCRIPTION
**Pull request by bjoernQ**
Fixes #135 

- use REF_TICK if requested frequency is too low
- change some confusing identifiers
- remove usage of esp-hal-common from examples
- re-export LEDC module in chip specific HALs

### CODE REVIEW

File: esp32s3-hal/examples/ledc.rs [hunk 1]
```diff
@@ -51,15 +51,17 @@ fn main() -> ! {
...
-            frequency: 24u32.kHz(),
-        })
-        .unwrap();
+    let res = lstimer0.configure(timer::config::Config {
+        duty: timer::config::Duty::Duty5Bit,
+        clock_source: timer::LSClockSource::APBClk,
+        frequency: 24u32.kHz(),
+    });
+
+    if res.is_err() {
```
Comment (MabezDev) [inline esp32s3-hal/examples/ledc.rs:62]: Let's clean this up a bit, probably okay to unwrap these errors now?

**Review by MabezDev — APPROVED** [review]
LGTM, just a quick note on the examples

File: esp32s3-hal/examples/ledc.rs (hunk 1 above)
Comment (bjoernQ) [reply esp32s3-hal/examples/ledc.rs]: Oh yes ... 🤦‍♂️ ... was just meant for my own testing. Good catch!
