### PR TITLE
Disable peripherals when unused

### LINKED ISSUE #1382: Implement `Drop` for drivers to restore peripherals to their default states
We currently are not implementing the `Drop` trait for (any of?) our drivers. For at least most of them, we should do so, and restore the peripherals back to their boot-default state.

I think perhaps GPIO pins would be an exception to this, and perhaps it does not make sense to implement this trait for other drivers as well. Some discussion will need to be had regarding this.

### PR DESCRIPTION
**Pull request by bjoernQ**
## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [ ] I have updated existing examples or added new ones (if applicable).
- [x] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [x] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [ ] I have added necessary changes to user code to the [Migration Guide](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/MIGRATING-0.21.md).
- [x] My changes are in accordance to the [esp-rs API guidelines](https://github.com/esp-rs/esp-hal/blob/main/documentation/API-GUIDELINES.md)

#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/documentation/CONTRIBUTING.md) and followed its instructions.

#### Description
Closes #1382 
Supercedes #2484 

This disables most peripherals when their driver gets fully dropped.

There are some peripherals which don't get touched
- UART0 (console logging would break)
- serial-jtag (console logging would break)
- systimer (we use it to get the time since boot)
- TIMG (we use TIMG0-LACT to get the time on ESP32)
- DMA (should be fine to do - but lets do it in a separate PR)
- LEDC (that driver will see a refactoring or rewrite)

others which we currently don't explicitly enable (some of them for reasons, but not all)

Additionally, peripherals are disabled in `init` - gives us a ~ 5mA advantage when not using them

#### Testing
- HIL-tests
- manual testing with logging enabled

### CODE REVIEW

File: esp-hal/src/hmac.rs [hunk 1]
```diff
@@ -345,3 +346,9 @@ impl<'d> Hmac<'d> {
         while self.is_busy() {}
     }
 }
+
+impl Drop for Hmac<'_> {
+    fn drop(&mut self) {
+        PeripheralClockControl::enable(PeripheralEnable::Hmac, true);
```
Comment (jessebraham) [inline esp-hal/src/hmac.rs:352]: Should this be `false`?

File: esp-hal/src/system.rs [hunk 2]
```diff
@@ -122,234 +134,245 @@ pub enum Peripheral {
...
 
 #[cfg(not(any(esp32c6, esp32h2)))]
 impl PeripheralClockControl {
-    /// Enables and resets the given peripheral
-    pub(crate) fn enable(peripheral: Peripheral) {
-        let system = unsafe { &*SYSTEM::PTR };
+    pub(crate) fn enable_forced(peripheral: Peripheral, enable: bool, force: bool) -> bool {
+        debug!("Enable {:?} {} {}", peripheral, enable, force);
+        critical_section::with(|_cs| {
+            if !force {
```
Comment (bugadani) [inline esp-hal/src/system.rs:182]: Force+disable should probably reset the refcounts, shouldn't it?

File: esp-hal/src/trace.rs [hunk 3]
```diff
@@ -203,14 +207,30 @@ where
     }
 }
 
+impl<T> Drop for Trace<'_, T>
+where
+    T: Instance,
+{
+    fn drop(&mut self) {
+        PeripheralClockControl::enable(self.peripheral.peripheral(), false);
```
Comment (Dominaezzz) [inline esp-hal/src/trace.rs:215]: Might be just me but `set_enable(false)` or `disable()` would be clearer that `enable(false)` .

File: esp-hal/src/lcd_cam/mod.rs [hunk 4]
```diff
@@ -31,22 +31,24 @@ pub struct LcdCam<'d, DM: crate::Mode> {
...
 }
 
 impl<'d> LcdCam<'d, Blocking> {
     /// Creates a new `LcdCam` instance.
     pub fn new(lcd_cam: impl Peripheral<P = LCD_CAM> + 'd) -> Self {
         crate::into_ref!(lcd_cam);
 
-        PeripheralClockControl::reset(system::Peripheral::LcdCam);
-        PeripheralClockControl::enable(system::Peripheral::LcdCam);
+        let guard = PeripheralGuard::new(system::Peripheral::LcdCam);
```
Comment (Dominaezzz) [inline esp-hal/src/lcd_cam/mod.rs:43]: Here you need to create two guards up front, one for cam and one for lcd.

(Might be worth having a version of `PeripheralGuard::new` that returns multiple guards at once, to avoid locking N times)

File: esp-hal/src/system.rs [hunk 5]
```diff
@@ -560,232 +585,200 @@ impl PeripheralClockControl {
...
+                    }
+                } else {
+                    let prev =
+                        PERIPHERAL_REF_COUNT[peripheral as usize].fetch_sub(1, Ordering::Relaxed);
+                    if prev > 1 {
+                        return false;
+                    }
+                };
+            } else if !enable {
+                PERIPHERAL_REF_COUNT[peripheral as usize].store(0, Ordering::Relaxed);
```
Comment (Dominaezzz) [inline esp-hal/src/system.rs:606]: I'm not sure what use case this is for but it could lead to an underflow if/when `fetch_sub` is called later.

File: esp-hal/src/lcd_cam/mod.rs (hunk 4 above)
Comment (bjoernQ) [reply esp-hal/src/lcd_cam/mod.rs:43]: > Here you need to create two guards up front, one for cam and one for lcd.

true 👍

File: esp-hal/src/trace.rs (hunk 3 above)
Comment (bjoernQ) [reply esp-hal/src/trace.rs:215]: I have no preference but I'm happy to change it if we agree on something else

File: esp-hal/src/system.rs (hunk 5 above)
Comment (bjoernQ) [reply esp-hal/src/system.rs:606]: The only case when it's forced disabled is in `esp_hal::init` - so it should be okay (given this is internal API only).
Would be nice if there was a saturating `fetch_add`/`fetch_sub` - on the other hand if it ever wraps it would be a bug in esp-hal

Comment (Dominaezzz) [reply esp-hal/src/system.rs:606]: In that case, instead of calling `store`, perhaps use `swap` and assert that the previous value is also zero.
In the `fetch_sub` case, you can assert that the prev value isn't zero.

At least if there is a bug in the hal, it'd be caught rather than subtly break

File: esp-hal/src/lcd_cam/cam.rs [hunk 6]
```diff
@@ -141,6 +144,8 @@ impl<'d> Camera<'d> {
         CH: DmaChannelConvert<<LCD_CAM as DmaEligible>::Dma>,
         P: RxPins,
     {
+        let guard = PeripheralGuard::new(crate::system::Peripheral::LcdCam);
```
Comment (bugadani) [inline esp-hal/src/lcd_cam/cam.rs:147]: Could this just be moved out of `Cam`?

Comment (bjoernQ) [reply esp-hal/src/lcd_cam/cam.rs:147]: Ah I see - you need a `Cam` to construct a `Camera`

File: esp-hal/src/system.rs [hunk 7]
```diff
@@ -122,234 +134,225 @@ pub enum Peripheral {
...
-            )
-        };
-        #[cfg(not(esp32))]
-        let (perip_clk_en0, perip_rst_en0) = { (&system.perip_clk_en0(), &system.perip_rst_en0()) };
+    fn enable_internal(peripheral: Peripheral, enable: bool) {
+        debug!("Enable {:?} {}", peripheral, enable);
 
-        #[cfg(any(esp32c2, esp32c3, esp32s2, esp32s3))]
-        let (perip_clk_en1, perip_rst_en1) = { (&system.perip_clk_en1(), &system.perip_rst_en1()) };
+        critical_section::with(|_cs| {
```
Comment (bjoernQ) [inline esp-hal/src/system.rs:183]: it's currently only called via `enable_forced` so we are already in a critical-section - not sure if it's ok to remove it here and have a comment (and maybe mark the function unsafe)

Comment (bugadani) [reply esp-hal/src/system.rs:183]: You can also change `force` into `Option<&CriticalSection>`

Comment (bjoernQ) [reply esp-hal/src/system.rs:183]: Not sure I understand that - I guess ``enable_forced` could add a paremeter `&CriticalSection` (not optional) but also the C6/H2 implementation should take it then .... I guess I will do that

Comment (bugadani) [reply esp-hal/src/system.rs:183]: Oh hm this is a bit hard to see in the diff view, so I missed where this comment was. If this function is only called in a critical section, just take a critical section (and don't bother with the forced part of my comment).

File: esp-hal/src/i2s/master.rs [hunk 8]
```diff
@@ -297,12 +300,15 @@ where
...
                 descriptors: rx_descriptors,
+                guard,
             },
             i2s_tx: TxCreator {
                 i2s,
                 tx_channel: channel.tx,
                 descriptors: tx_descriptors,
+                guard: PeripheralGuard::new(peripheral),
             },
+            guard: PeripheralGuard::new(peripheral),
```
Comment (bugadani) [inline esp-hal/src/i2s/master.rs:311]: It's a small thing but I don't think the outer driver needs a guard. It costs a bit of memory and maybe a few cycles, and the Tx/Rx guard are sufficient.

File: esp-hal/src/i2s/parallel.rs [hunk 9]
```diff
@@ -220,8 +221,8 @@ where
         channel.runtime_ensure_compatible(&i2s);
         let channel = channel.degrade();
 
-        PeripheralClockControl::reset(i2s.peripheral());
-        PeripheralClockControl::enable(i2s.peripheral());
+        let guard = PeripheralGuard::new(i2s.peripheral());
```
Comment (bugadani) [inline esp-hal/src/i2s/parallel.rs:224]: It seems at one point the PeripheralGuard won over manually managing clocks. Would you consider updating AES/ADC, too?

File: esp-hal/src/mcpwm/mod.rs [hunk 10]
```diff
@@ -181,6 +181,7 @@ impl<'d, PWM: PwmPeripheral> McPwm<'d, PWM> {
             operator0: Operator::new(),
             operator1: Operator::new(),
             operator2: Operator::new(),
+            _guard: guard,
```
Comment (bugadani) [inline esp-hal/src/mcpwm/mod.rs:184]: I think each Operator (and Timer, I guess) needs its own guard, otherwise it's too easy to accidentally drop the peripheral.

Comment (bugadani) [reply esp-hal/src/mcpwm/mod.rs:184]: Nevermind, I didn't know Operators have guards, in this case this outer one isn't necessary.

File: esp-hal/src/parl_io.rs [hunk 11]
```diff
@@ -1114,13 +1141,15 @@ where
...
     {
+        let guard = PeripheralGuard::new(crate::system::Peripheral::ParlIo);
         internal_init(frequency)?;
 
         Ok(Self {
             tx: TxCreator {
                 tx_channel: dma_channel.tx.degrade(),
                 descriptors,
             },
+            _guard: guard,
```
Comment (bugadani) [inline esp-hal/src/parl_io.rs:1152]: I think this needs to be in the TxCreator, otherwise we can move `tx` out, but drop the peripheral.

File: esp-hal/src/rmt.rs [hunk 12]
```diff
@@ -911,29 +949,38 @@ mod impl_for_chip {
                 peripheral,
                 channel0: ChannelCreator {
                     phantom: PhantomData,
+                    _guard: PeripheralGuard::new(crate::system::Peripheral::Rmt),
```
Comment (bugadani) [inline esp-hal/src/rmt.rs:952]: I **think** the channelcreators don't need to enable the clocks, until the first channel is constructed.

**Comment by bugadani** [comment]
In general, I like the idea of PeripheralGuard. I'd prefer it to be generic and zero-sized, but I don't see that happening with type erased peripherals. Maybe we could have two variants, one for ZST peripherals and one for erased ones.

Looking closely at the code, I can see that this PR was done mostly mechanically, there are a few places where a guard isn't necessary (RMT, and some others), or some where it looks not entirely correct to my eyes (PARL_IO).

File: esp-hal/src/rmt.rs [hunk 13]
```diff
@@ -969,12 +1017,18 @@ mod impl_for_chip {
...
-#[derive(Debug)]
 pub struct Channel<M, const CHANNEL: u8>
 where
     M: crate::Mode,
 {
     phantom: PhantomData<M>,
+    _guard: PeripheralGuard,
+}
+
+impl<M: crate::Mode, const CHANNEL: u8> core::fmt::Debug for Channel<M, CHANNEL> {
```
[the remark this answers is not in the document]
Comment (bjoernQ) [reply esp-hal/src/rmt.rs:1028]: ah yeah - having `Debug` on the `PeripheralGuard` is actually better 👍 

I think in many places we unconditionally implement Debug to allow `unwrap` - not having it would (conditionally) would be a breaking change (which we might or might not want)

File: esp-hal/src/mcpwm/mod.rs (hunk 10 above)
Comment (bjoernQ) [reply esp-hal/src/mcpwm/mod.rs:184]: they all include guards

File: esp-hal/src/rmt.rs (hunk 12 above)
Comment (bjoernQ) [reply esp-hal/src/rmt.rs:952]: ah I remember - problem is a user can take the creator out, drop `Rmt` and then create a channel from the creator - we would then disable the already pre-configured peripheral

Comment (bjoernQ) [reply esp-hal/src/rmt.rs:952]: But we probably don't need the guard on `Rmt` itself then

**Review by bugadani — APPROVED** [review]

**Review by MabezDev — CHANGES_REQUESTED** [review]

File: hil-test/tests/spi_half_duplex_write.rs [hunk 14]
```diff
@@ -112,7 +112,8 @@ mod tests {
             )
             .map_err(|e| e.0)
             .unwrap();
-        transfer.wait();
+        // dropping SPI would make us see an additional edge - so let's keep SPI alive
```
[the remark this answers is not in the document]
Comment (bjoernQ) [reply hil-test/tests/spi_half_duplex_write.rs:115]: When we reset the peripheral, we also reset CTRL.D_POL ( to 1) so MOSI is idle-high

So, it looks like this:

image

See how MOSI is set to high after resetting (near the marker)

BTW we can also see that effect on `main` before the initial transaction

image

There we see MOSI shows a "bump" between reset and setting D_POL to 0

File: examples/src/bin/spi_loopback.rs [hunk 15]
```diff
@@ -46,8 +46,8 @@ fn main() -> ! {
         },
     )
     .with_sck(sclk)
-    .with_mosi(miso_mosi)
-    .with_miso(miso)
+    .with_miso(miso) // order matters
+    .with_mosi(miso_mosi) // order matters
```
[the remark this answers is not in the document]
Comment (bugadani) [reply examples/src/bin/spi_loopback.rs:50]: Well now that PR is closed, the problem is back with us 🥲

**Review by jessebraham — APPROVED** [review]
Changes LGTM, but will wait for @MabezDev to approve before merging since he had requested changes

**Review by MabezDev — APPROVED** [review]
Thanks!
