### PR TITLE
Fix ESP32 PSRAM (in combination with esp-storage)

### LINKED ISSUE #3229: On ESP32 esp-storage doesn't work together with PSRAM (psram feature flag enabled)
## Bug description
On ESP32 When trying to read from flash storage using esp-storage, data isn't read correctly if `psram` feature flag is enabled.
More detailed information is available in: #3220

A summary of the technical root cause from @bjoernQ in that discussion:  

> esp-storage is accessing SPI0 and SPI1 directly on ESP32 and having PSRAM enabled might get them into unexpected states.
> 
> For S2/S3 we are using ROM-functions which apparently account for that

## To Reproduce

The example at `examples/src/bin/flash_read_write.rs` doesn't work if psram is enabled. 

## Environment

- Target device: ESP32
- Crate name and version: 0.23.1 and main

### PR DESCRIPTION
**Pull request by bjoernQ**
## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [ ] I have updated existing examples or added new ones (if applicable).
- [x] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [x] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [ ] I have added necessary changes to user code to the [Migration Guide](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/MIGRATING-0.21.md).
- [x] My changes are in accordance to the [esp-rs developer guidelines](https://github.com/esp-rs/esp-hal/blob/main/documentation/DEVELOPER-GUIDELINES.md)

#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/documentation/CONTRIBUTING.md) and followed its instructions.

#### Description
Fixes #3229

#### Testing
Added CI test - additionally you can use this code (modified read_write_flash example)

```rust
//! Writes and reads flash memory.
//!
//! See https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/partition-tables.html#built-in-partition-tables

//% FEATURES: esp-storage esp-hal/unstable  esp-alloc/internal-heap-stats esp-hal/psram
//% CHIPS: esp32 esp32c2 esp32c3 esp32c6 esp32h2 esp32s2 esp32s3

#![no_std]
#![no_main]

use embedded_storage::{ReadStorage, Storage};
use esp_backtrace as _;
use esp_bootloader_esp_idf::partitions;
use esp_hal::main;
use esp_println::println;
use esp_storage::FlashStorage;

extern crate alloc;

use alloc::{string::String, vec::Vec};

use esp_alloc as _;

esp_bootloader_esp_idf::esp_app_desc!();
use esp_hal::psram;

fn init_psram_heap(start: *mut u8, size: usize) {
    unsafe {
        esp_alloc::HEAP.add_region(esp_alloc::HeapRegion::new(
            start,
            size,
            esp_alloc::MemoryCapability::External.into(),
        ));
    }
}

#[main]
fn main() -> ! {
    esp_println::logger::init_logger_from_env();

    let peripherals = esp_hal::init(esp_hal::Config::default());

    let (start, size) = psram::psram_raw_parts(&peripherals.PSRAM);
    init_psram_heap(start, size);

    println!("Going to access PSRAM");
    let mut large_vec = Vec::<u32>::with_capacity(500 * 1024 / 4);

    for i in 0..(500 * 1024 / 4) {
        large_vec.push((i & 0xff) as u32);
    }

    println!("vec size = {} bytes", large_vec.len() * 4);
    println!("vec address = {:p}", large_vec.as_ptr());
    println!("vec[..100] = {:?}", &large_vec[..100]);

    let string = String::from("A string allocated in PSRAM");
    println!("'{}' allocated at {:p}", &string, string.as_ptr());

    println!("{}", esp_alloc::HEAP.stats());

    let mut flash = FlashStorage::new();
    println!("Flash size = {}", flash.capacity());

    let mut pt_mem = [0u8; partitions::PARTITION_TABLE_MAX_LEN];
    let pt = partitions::read_partition_table(&mut flash, &mut pt_mem).unwrap();

    for i in 0..pt.len() {
        let raw = pt.get_partition(i).unwrap();
        println!("{:?}", raw);
    }
    println!();

    // The app descriptor (if present) is contained in the first 256 bytes
    // of an app image, right after the image header (24 bytes) and the first section header (8 bytes)
    let mut app_desc = [0u8; 256];
    pt.find_partition(partitions::PartitionType::App(
        partitions::AppPartitionSubType::Factory,
    ))
    .unwrap()
    .unwrap()
    .as_embedded_storage(&mut flash)
    .read(32, &mut app_desc)
    .unwrap();
    println!("App descriptor dump {:02x?}", app_desc);
    println!();

    let nvs = pt
        .find_partition(partitions::PartitionType::Data(
            partitions::DataPartitionSubType::Nvs,
        ))
        .unwrap()
        .unwrap();
    let mut nvs_partition = nvs.as_embedded_storage(&mut flash);

    let mut bytes = [0u8; 32];
    println!("NVS partition size = {}", nvs_partition.capacity());
    println!();

    let offset_in_nvs_partition = 0;

    nvs_partition
        .read(offset_in_nvs_partition, &mut bytes)
        .unwrap();
    println!(
        "Read from {:x}:  {:02x?}",
        offset_in_nvs_partition,
        &bytes[..32]
    );

    bytes[0x00] = bytes[0x00].wrapping_add(1);
    bytes[0x01] = bytes[0x01].wrapping_add(2);
    bytes[0x02] = bytes[0x02].wrapping_add(3);
    bytes[0x03] = bytes[0x03].wrapping_add(4);
    bytes[0x04] = bytes[0x04].wrapping_add(1);
    bytes[0x05] = bytes[0x05].wrapping_add(2);
    bytes[0x06] = bytes[0x06].wrapping_add(3);
    bytes[0x07] = bytes[0x07].wrapping_add(4);

    nvs_partition
        .write(offset_in_nvs_partition, &bytes)
        .unwrap();
    println!(
        "Written to {:x}: {:02x?}",
        offset_in_nvs_partition,
        &bytes[..32]
    );

    let mut reread_bytes = [0u8; 32];
    nvs_partition.read(0, &mut reread_bytes).unwrap();
    println!(
        "Read from {:x}:  {:02x?}",
        offset_in_nvs_partition,
        &reread_bytes[..32]
    );

    println!();
    println!("Reset (CTRL-R in espflash) to re-read the persisted data.");

    loop {}
}

```

### CODE REVIEW

File: esp-hal/src/soc/esp32/psram.rs [hunk 1]
```diff
@@ -966,7 +965,7 @@ pub(crate) mod utils {
 
             // Wait for SPI0 to idle
             loop {
-                if spi.ext2().read().bits() == 0 {
+                if SPI1::regs().ext2().read().bits() == 0 {
```
Comment (bugadani) [inline esp-hal/src/soc/esp32/psram.rs:968]: Can we turn this into a `while`, please?

**Comment by bugadani** [comment]
Was the issue also triggered by a flash read? If so, we may add a test case to alloc_psram instead of some manually modified example

**Comment by bjoernQ** [comment]
> Was the issue also triggered by a flash read? If so, we may add a test case to alloc_psram instead of some manually modified example

good idea .... yes .... it was also reading garbage before 👍

**Review by bugadani — APPROVED** [review]

**Review by MabezDev — APPROVED** [review]
Thanks!
