### PR TITLE
Make sure to call enable for a few BLE functions on later NPL based chips

### LINKED ISSUE #5454: ESP32-C5: BLE controller asserts `adiList_stack_addAdiList:31 0 0` on extended scan (LE_Set_Extended_Scan_Enable)
## Bug description                                          
                                                                                        
On ESP32-C5, performing a BLE extended scan via LE_Set_Extended_Scan_Enable crashes   
with:                                                           
                                                                                               
`  panicked at 'ASSERT adiList_stack_addAdiList:31 0 0'         `                                  
                                                          
A legacy scan (LE_Set_Scan_Parameters / LE_Set_Scan_Enable, the pre-BT5 path) on identical
hardware and software is stable indefinitely, only the extended-scan path crashes.

## To Reproduce

1. Build the reproducer below with --release for esp32c5 and flash it to an ESP32-C5-WROOM-1
module.
2. Watch RTT - the assertion fires within seconds to a few minutes of ble scan starting.
3. Replace scanner.scan_ext(&cfg) with scanner.scan(&cfg) in the same code, then no assertion, scan
 runs just fine.

Verified to reproduce on esp-radio v0.18.0. Repro tested with a
no-op EventHandler; the assertion does not require any user-side report processing,  just
enabling extended scan in an environment with extended-adv traffic is enough.

```
#![no_std]
#![no_main]

use bt_hci::controller::ExternalController;
use embassy_executor::Spawner;
use embassy_time::{Duration, Timer};
use esp_hal::clock::CpuClock;
use esp_hal::timer::timg::TimerGroup;
use esp_radio::ble::controller::BleConnector;
use panic_rtt_target as _;
use trouble_host::prelude::*;

extern crate alloc;

esp_bootloader_esp_idf::esp_app_desc!();

const CONNECTIONS_MAX: usize = 1;
const L2CAP_CHANNELS_MAX: usize = 1;

#[esp_rtos::main]
async fn main(_spawner: Spawner) -> ! {
  rtt_target::rtt_init_defmt!();

  let peripherals = esp_hal::init(esp_hal::Config::default().with_cpu_clock(CpuClock::max()));

  esp_alloc::heap_allocator!(#[esp_hal::ram(reclaimed)] size: 65536);
  esp_alloc::heap_allocator!(size: 64 * 1024);

  let timg0 = TimerGroup::new(peripherals.TIMG0);
  let sw = esp_hal::interrupt::software::SoftwareInterruptControl::new(peripherals.SW_INTERRUPT);
  esp_rtos::start(timg0.timer0, sw.software_interrupt0);

  let transport = BleConnector::new(peripherals.BT, Default::default()).unwrap();
  let ble_controller = ExternalController::<_, 1>::new(transport);
  let mut resources: HostResources<DefaultPacketPool, CONNECTIONS_MAX, L2CAP_CHANNELS_MAX> =
      HostResources::new();
  let stack = trouble_host::new(ble_controller, &mut resources)
      .set_random_address(Address::random([0xff, 0x8f, 0x1b, 0x05, 0xe4, 0xff]));
  let host = stack.build();
  let mut runner = host.runner;
  let mut scanner = Scanner::new(host.central);

  struct H;
  impl EventHandler for H {}
  let h = H;

  let cfg = ScanConfig {
      active: false,
      phys: PhySet::M1,
      interval: Duration::from_millis(500),
      window: Duration::from_millis(100),
      timeout: Duration::from_secs(0),
      ..Default::default()
  };

  defmt::info!("ble scan starting");

  embassy_futures::join::join(
      async {
          loop {
              let _ = runner.run_with_handler(&h).await;
          }
      },
      async {
          loop {
              let _session = scanner.scan_ext(&cfg).await.unwrap();
              Timer::after(Duration::from_secs(5)).await;
          }
      },
  )
  .await;

  unreachable!()
}
```

Crashed with:
```[INFO ] ble scan starting
[ERROR] panicked at 'ASSERT adiList_stack_addAdiList:31 0 0'
[ERROR] panicked at /home/patrik/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/defmt-1.0.1/src/lib.rs:385:5:
explicit panic
```

## Things tried that did not help:
- Bumping the controller's dup lists to the max via esp_radio::ble::Config::def
ault().with_ll_adv_dup_list_count(100).with_ll_rsp_dup_list_count(100). With the default 20,
average reports until crash is ~5; with 100 it is ~30–60. Eventually crashes either way.
- Patching esp-radio os_adapter_esp32c5.rs ble_ll_scan_phy_number: 2 => 1.
- Patching esp-radio os_adapter_esp32c5.rs scan_allow_adi_filter: 0 => 1.
- Patching trouble-host host/src/scan.rs:72 FilterDuplicates::Disabled => Enabled.
- Calling set_random_address before .build().
- Short cycled sessions (e.g. 1 s scan + 500 ms idle) so the controller frees per-scan state
more often.

## Expected behavior

LE_Set_Extended_Scan_Enable on the ESP32-C5 controller should not assert and crash the firmware
 when an extended advertising frame is received. 

## Environment

- Target device: ESP32-C5-WROOM-1 (Dev-Kit)
- Crate name and version: esp-hal 1.1.0, esp-radio 0.18.0
- Other relevant deps: esp-rtos 0.3.0, bt-hci 0.8.0, trouble-host 0.6.0, embassy-executor
0.10.0, embassy-time 0.5.0

### PR DESCRIPTION
**Pull request by bjoernQ**
Fixes #5454 for H2, C6, C61, C5

I guess in #3071 we should make sure to cover this (noting it here to get this linked to the issue so we don't forget about it)

### CODE REVIEW

**Comment by bugadani** [comment]
Can we test this somehow? 🥺

**Comment by bjoernQ** [comment]
> Can we test this somehow? 🥺

when we have #3071 hopefully yes - just running it in HIL won't help since we need to receive an ext-advertising package to trigger the crash

**Comment by bugadani** [comment]
what about a QA test in the mean time? do any of them trigger the panic currently?

**Comment by bjoernQ** [comment]
> what about a QA test in the mean time? do any of them trigger the panic currently?

yeah - a qa-test might be a good idea - would need some instructions how to really test it 🤔

File: qa-test/src/bin/ext_adv_scan.rs [hunk 1]
```diff
@@ -0,0 +1,94 @@
+//! A check that extended-advertisement scanning works.
+//!
+//! To really test this you need a way to have large advertisements received.
+//!
+//! e.g. on Windows use `Bluetooth LE Explorer` - use `Advertisement Beacon`,
+//! make sure to enable "Use Extended Format" and some payload.
+//! Enable advertising.
+
+//% FEATURES: esp-radio esp-radio/ble esp-hal/unstable
+//% CHIPS: esp32s3 esp32h2 esp32c2 esp32c3 esp32c5 esp32c6 esp32c61
```
Comment (bugadani) [inline qa-test/src/bin/ext_adv_scan.rs:12]: Is esp32 not relevant here, or not working and we're silently ignoring it? s3/c3 are also btdm, not npl, so they aren't affected by this PR either.

Comment (bugadani) [reply qa-test/src/bin/ext_adv_scan.rs:12]: hmm esp32 fails with 

```
====================== PANIC ======================
panicked at src\bin\ext_adv_scan.rs:72:60:
called `Result::unwrap()` on an `Err` value: BleHost(Hci(Unknown HCI Command))
```

Comment (bjoernQ) [reply qa-test/src/bin/ext_adv_scan.rs:12]: ESP32 is BLE 4.2 - it's not supported before 5.0

Comment (bjoernQ) [reply qa-test/src/bin/ext_adv_scan.rs:12]: >  s3/c3 are also btdm, not npl, so they aren't affected by this PR either.

Yeah but checking it works there shouldn't hurt

Comment (bugadani) [reply qa-test/src/bin/ext_adv_scan.rs:12]: Please add a note for dummies like me who don't know which BLE version is relevant here.

**Review by bugadani — APPROVED** [review]
