### PR TITLE
I2C error recovery

### LINKED ISSUE #1790: When using I2C + shared bus + embassy, if there is no slave device at the accessed address, subsequent I2C operations will send the same signal repeatedly.
I am just a hobbyist, so my description might not be very clear. Please bear with me.

My program runs on an ESP32-C3, and I use `i2c0`. When I alternately access devices at two different addresses in two embassy tasks, if one of the slave devices is offline, the signals sent by the other task to the I2C bus always have the same address as the former, instead of the one specified in the code.

Here is a snippet of my code:

```rust
#[embassy_executor::task]
async fn run_i2c_a(
    dev: &'static mut I2cDevice<'static, CriticalSectionRawMutex, I2C<'static, I2C0, Async>>,
) {
    let addr = 0x0a;

    log::info!("run_i2c addr: 0x{:02x}", addr);
    loop {
        Timer::after(Duration::from_millis(1000)).await;
        match dev.write(addr, &[0x11]).await {
            Ok(_) => {
                log::info!("set addr: 0x{:02x}", addr);
            }
            Err(err) => {
                log::error!("failed to set addr: 0x{:02x}. {:?}", addr, err);
            }
        }

    }
}

#[embassy_executor::task]
async fn run_i2c_b(
    dev: &'static mut I2cDevice<'static, CriticalSectionRawMutex, I2C<'static, I2C0, Async>>,
) {
    let addr = 0x0b;

    log::info!("run_i2c addr: 0x{:02x}", addr);
    loop {
        Timer::after(Duration::from_millis(1000)).await;
        match dev.write(addr, &[0x11]).await {
            Ok(_) => {
                log::info!("set addr: 0x{:02x}", addr);
            }
            Err(err) => {
                log::error!("failed to set addr: 0x{:02x}. {:?}", addr, err);
            }
        }

    }
}
```

What I expect is that if one or both of 0x4a and 0x4b are offline, the tasks can still alternately attempt to access them (I am hoping to access the slave device when it comes back online after being disconnected for some reason). Currently, both 0x4a and 0x4b are nonexistent devices. The signal I sniffed with a logic analyzer is as shown below, where it continuously tries to access 0x4a. From the log outputs I added to the code, I can confirm that the code runs alternately, but the signal sent is stuck on the same value.

image

`espflash-monitor` log:

```shell
INFO - starting
INFO - run_i2c addr: 0x4b
INFO - run_i2c addr: 0x4a
ERROR - failed to set addr: 0x4b. I2c(AckCheckFailed)
ERROR - failed to set addr: 0x4a. I2c(ExecIncomplete)
ERROR - failed to set addr: 0x4b. I2c(ExecIncomplete)
ERROR - failed to set addr: 0x4a. I2c(ExecIncomplete)
ERROR - failed to set addr: 0x4b. I2c(ExecIncomplete)
ERROR - failed to set addr: 0x4a. I2c(ExecIncomplete)
ERROR - failed to set addr: 0x4b. I2c(ExecIncomplete)
ERROR - failed to set addr: 0x4a. I2c(ExecIncomplete)
ERROR - failed to set addr: 0x4b. I2c(ExecIncomplete)
ERROR - failed to set addr: 0x4a. I2c(ExecIncomplete)

...
```

i2c log:
```txt
1958420-1958490 I²C: Address/Data: Address write: 4B
1958409-1958409 I²C: Address/Data: Start
1958490-1958500 I²C: Address/Data: Write
1958500-1958510 I²C: Address/Data: NACK
1958517-1958517 I²C: Address/Data: Stop
1964852-1964852 I²C: Address/Data: Start
1964863-1964933 I²C: Address/Data: Address write: 4A
1964933-1964943 I²C: Address/Data: Write
1964943-1964953 I²C: Address/Data: NACK
1964960-1964960 I²C: Address/Data: Stop
2964900-2964900 I²C: Address/Data: Start
2964911-2964981 I²C: Address/Data: Address write: 4A
2964981-2964991 I²C: Address/Data: Write
2964991-2965001 I²C: Address/Data: NACK
2965008-2965008 I²C: Address/Data: Stop
2965301-2965301 I²C: Address/Data: Start
2965311-2965381 I²C: Address/Data: Address write: 4A
2965381-2965391 I²C: Address/Data: Write
2965391-2965401 I²C: Address/Data: NACK
2965408-2965408 I²C: Address/Data: Stop
3965284-3965284 I²C: Address/Data: Start
3965294-3965364 I²C: Address/Data: Address write: 4A
3965364-3965374 I²C: Address/Data: Write
3965374-3965384 I²C: Address/Data: NACK
3965391-3965391 I²C: Address/Data: Stop
3965692-3965692 I²C: Address/Data: Start
3965702-3965773 I²C: Address/Data: Address write: 4A
3965773-3965783 I²C: Address/Data: Write
3965782-3965792 I²C: Address/Data: NACK
3965800-3965800 I²C: Address/Data: Stop
4965651-4965651 I²C: Address/Data: Start
4965661-4965731 I²C: Address/Data: Address write: 4A
4965731-4965741 I²C: Address/Data: Write
4965741-4965751 I²C: Address/Data: NACK
4965759-4965759 I²C: Address/Data: Stop
4966072-4966072 I²C: Address/Data: Start

...
```

I am not sure if I am using it incorrectly or if there is some unexpected situation.

Here is the [ minimal reproducible repository](https://github.com/IvanLi-CN/esp-i2c-shared-bus-embassy-issue) related to the issue. You can pull this repository to test, and no slave device needs to be connected.

### PR DESCRIPTION
**Pull request by bjoernQ**
## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [x] I have updated existing examples or added new ones (if applicable).
- [x] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [x] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [ ] I have added necessary changes to user code to the [Migration Guide](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/MIGRATING-0.21.md).
- [x] My changes are in accordance to the [esp-rs API guidelines](https://github.com/esp-rs/esp-hal/blob/main/documentation/API-GUIDELINES.md)

#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/documentation/CONTRIBUTING.md) and followed its instructions.

#### Description
Fixes #1790

Recovering from an error didn't work as expected for I2C - this does it "the hard way" by resetting and re-initializing the whole peripheral (since nothing else seemed to help).

In theory a user could drop the driver and re-create it but in real-life code that can become very cumbersome - so now after running into an error the peripheral is always reset and re-initialized

#### Testing
I adapted the test to check the undesired behavior.

Additionally having this in examples resembles the code from the linked issue and can be used to test this locally (make sure to have something detectable connected)
```rust
//! - SDA => GPIO4
//! - SCL => GPIO5

//% CHIPS: esp32 esp32c2 esp32c3 esp32c6 esp32h2 esp32s2 esp32s3

#![no_std]
#![no_main]

use esp_backtrace as _;
use esp_hal::{gpio::Io, i2c::I2C, prelude::*};
use esp_println::println;

#[entry]
fn main() -> ! {
    let mut peripherals = esp_hal::init(esp_hal::Config::default());

    let mut io = Io::new(peripherals.GPIO, peripherals.IO_MUX);

    // Create a new peripheral object with the described wiring and standard
    // I2C clock speed:
    let mut i2c0 = I2C::new(
        &mut peripherals.I2C0,
        &mut io.pins.gpio4,
        &mut io.pins.gpio5,
        100.kHz(),
    );

    let delay = esp_hal::delay::Delay::new();

    for addr in 0..=127 {
        println!("Scan {}", addr as u8);
        let res = i2c0.read(addr, &mut [0]);

        match res {
            Ok(_) => println!("Dev Found @ {}", addr as u8),
            Err(e) => {
                println!("No Dev {:?}", e);
            }
        }

        delay.delay_millis(5);
    }

    loop {}
}
```

### CODE REVIEW

File: esp-hal/src/i2c.rs [hunk 1]
```diff
@@ -195,12 +209,12 @@ where
 {
     /// Reads enough bytes from slave with `address` to fill `buffer`
     pub fn read(&mut self, address: u8, buffer: &mut [u8]) -> Result<(), Error> {
-        self.peripheral.master_read(address, buffer)
+        maybe_recover!(self, { self.peripheral.master_read(address, buffer) })
```
Comment (bugadani) [inline esp-hal/src/i2c.rs:212]: This is a very confusing way of writing code similar to

```rust
self.peripheral_master_read(address, buffer).or_else(|err| { self.recover(); err})
```

Can we make do without the macro?

Comment (bjoernQ) [reply esp-hal/src/i2c.rs:212]: Matter of taste but sure - no preference

Comment (bugadani) [reply esp-hal/src/i2c.rs:212]: To me the macro reads like "if self is an error, call the block" which is obvious nonsense 🤷‍♂️

File: esp-hal/src/i2c.rs [hunk 2]
```diff
@@ -387,6 +423,25 @@ where
             crate::interrupt::enable(T::interrupt(), handler.priority()).unwrap();
         }
     }
+
+    /// Recover from error condition
+    pub fn recover(&self) {
```
Comment (MabezDev) [inline esp-hal/src/i2c.rs:428]: This should probably be `&mut self` right? If it needs to be `&self` for internal lifetime reasons, we should have two methods one public and one private.

**Review by MabezDev — CHANGES_REQUESTED** [review]

File: esp-hal/src/i2c.rs (hunk 2 above)
Comment (bjoernQ) [reply esp-hal/src/i2c.rs:428]: ah - I didn't plan to make this public at all

if public it needs to be `&mut self` of course - I didn't thought this would be something we want in public API, do we?
If yes I will expose a public variant taking `&mut self`

Comment (MabezDev) [reply esp-hal/src/i2c.rs:428]: Let's put this back to private. In theory the driver should self recover, and if it doesn't that's a bug that users should report.

**Review by MabezDev — APPROVED** [review]
I looked at how esp-idf handles time outs etc, and they also just queue up full resets of the peripheral when an error occurs. 

LGTM

**Review by bugadani — APPROVED** [review]
Thanks!
