### PR TITLE
More validation and `# Errors` entries

### LINKED ISSUE #2839: Peripheral drivers should validate configuration before applying it to hardware
`apply_config` is fallible, which means two things:

- It can fail
- The user can ignore the failure and keep using the driver

Because of this, we should validate the whole configuration before we apply it to the hardware.

### PR DESCRIPTION
**Pull request by playfulFence**
Introduces more validation for SPI and UART, allows setting baudrate tolerance for UART config, adds more `# Errors` entries
closes #2839

### CODE REVIEW

File: esp-hal/src/spi/master.rs [hunk 1]
```diff
@@ -596,6 +596,14 @@ impl Config {
     fn raw_clock_reg_value(&self) -> Result<u32, ConfigError> {
         self.reg
     }
+
+    fn validate(&self) -> Result<(), ConfigError> {
+        // Max supported frequency is 80Mhz
+        if self.frequency > HertzU32::MHz(80) {
```
Comment (bugadani) [inline esp-hal/src/spi/master.rs:602]: Can't we not detect if the user requested a frequency, but the dividers are at their limits? SPI has a lower limit, too, something on the order of 80kHz that I hit in some tests.

File: esp-hal/src/spi/master.rs [hunk 2]
```diff
@@ -425,6 +425,19 @@ pub enum ClockSource {
     // Xtal,
 }
 
+/// Defines how strictly the requested frequency must be met.
+#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
+#[cfg_attr(feature = "defmt", derive(defmt::Format))]
+pub enum FrequencyTolerance {
```
[the remark this answers is not in the document]
Comment (MabezDev) [reply esp-hal/src/spi/master.rs:431]: and also do the same for the other tolerance related type in the other drivers.

**Review by MabezDev — CHANGES_REQUESTED** [review]
Not sure if you're looking for review feedback now, but I guess you're gunna get it :D.

In general the approach looks sound. I think that we should document the specific variants that can be returned (this should be possible with rustdoc). We should probably mark the tolerance bits as unstable for now, just so we can give it some time to soak in. Finally, tests plz :D.

File: esp-hal/src/spi/master.rs [hunk 3]
```diff
@@ -602,7 +618,22 @@ struct SpiPinGuard {
...
+    UnsupportedFrequency,
+}
+
+impl core::error::Error for ConfigError {}
+
+impl core::fmt::Display for ConfigError {
+    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
+        match self {
+            ConfigError::UnsupportedFrequency => {
+                write!(f, " The requested frequency is not supported")
```
Comment (bjoernQ) [inline esp-hal/src/spi/master.rs:632]: no need for the leading space

File: esp-hal/src/spi/master.rs [hunk 4]
```diff
@@ -1071,9 +1110,10 @@ where
     ///
     /// # Errors
     ///
-    /// The corresponding error variant from [`Error`] will be returned if
+    /// [`Error::FifoSizeExeeded`] or [`Error::Unsupported`] will be returned if
     /// passed buffer is bigger than FIFO size or if buffer is empty (currently
```
Comment (bjoernQ) [inline esp-hal/src/spi/master.rs:1114]: not to be resolved in this PR but I think in some cases passing zero-length buffers are no-ops and in some cases we return errors - we should be consistent here (IMHO it should be a no-op but something to discuss)

File: esp-hal/src/spi/master.rs [hunk 5]
```diff
@@ -1554,7 +1594,10 @@ mod dma {
         }
 
         /// Change the bus configuration.
-        // FIXME: when https://github.com/esp-rs/esp-hal/issues/2839 is resolved, add an appropriate `# Error` entry.
+        ///
+        /// # Errors.
+        /// If frequency passed in config exceeds 80Mhz, a corresponding
```
Comment (bjoernQ) [inline esp-hal/src/spi/master.rs:1599]: we should tell the real limit (which is different for H2) - we already do it in other places

File: esp-hal/src/uart.rs [hunk 6]
```diff
@@ -2405,6 +2478,32 @@ impl Info {
         self.regs()
             .clkdiv()
             .write(|w| unsafe { w.clkdiv().bits(divider_integer).frag().bits(divider_frag) });
+
+        let actual_baud = self.get_baudrate(clk);
```
Comment (bjoernQ) [inline esp-hal/src/uart.rs:2482]: maybe it's worth to deduplicate the code block (we have it three times)

File: esp-hal/src/uart.rs [hunk 7]
```diff
@@ -2547,6 +2698,32 @@ impl Info {
         txfifo_rst(self.regs(), true);
         txfifo_rst(self.regs(), false);
     }
+
+    fn get_baudrate(&self, clk: u32) -> u32 {
```
Comment (jessebraham) [inline esp-hal/src/uart.rs:2702]: There are a number of identical lines in each branch here, probably could use some de-duplication.

File: esp-hal/src/uart.rs [hunk 8]
```diff
@@ -329,6 +349,20 @@ impl Default for RxConfig {
...
+    #[instability::unstable]
+    pub fn with_baudrate_tolerance(mut self, tolerance: BaudrateTolerance) -> Self {
+        self.baudrate_tolerance = match tolerance {
+            BaudrateTolerance::Exact => BaudrateTolerance::Exact,
+            BaudrateTolerance::Closest => BaudrateTolerance::Closest,
+            BaudrateTolerance::ErrorPercent(percentage) => {
+                assert!(percentage > 0 && percentage <= 100);
+                BaudrateTolerance::ErrorPercent(percentage)
+            }
+        };
```
Comment (jessebraham) [inline esp-hal/src/uart.rs:362]:
```suggestion
        if let BaudrateTolerance::ErrorPercent(percentage) = tolerance {
            assert!(percentage > 0 && percentage <= 100);
        }
        self.baudrate_tolerance = tolerance;
```

Any reason not to simplify this?

**Review by bjoernQ — APPROVED** [review]
LGTM

File: esp-hal/src/spi/master.rs [hunk 9]
```diff
@@ -666,7 +696,9 @@ where
 
 impl<'d> Spi<'d, Blocking> {
     /// Constructs an SPI instance in 8bit dataframe mode.
-    // FIXME: when https://github.com/esp-rs/esp-hal/issues/2839 is resolved, add an appropriate `# Error` entry.
+    ///
+    /// # Errors
+    /// See [`Spi::apply_config`].
```
Comment (SergioGasquez) [inline esp-hal/src/spi/master.rs:701]:
```suggestion
    /// # Errors
    ///
    /// See [`Spi::apply_config`].
```

Just to be consistent with the other comments, Ill leave an empty line after the header

File: esp-hal/src/spi/master.rs [hunk 10]
```diff
@@ -983,7 +1015,13 @@ where
     }
 
     /// Change the bus configuration.
-    // FIXME: when https://github.com/esp-rs/esp-hal/issues/2839 is resolved, add an appropriate `# Error` entry.
+    ///
+    /// # Errors.
+    /// If frequency passed in config exceeds
```
Comment (SergioGasquez) [inline esp-hal/src/spi/master.rs:1020]:
```suggestion
    /// # Errors
    ///
    /// If frequency passed in config exceeds
```

Add empty line and remove the final dot

File: esp-hal/src/spi/master.rs [hunk 11]
```diff
@@ -1554,7 +1593,13 @@ mod dma {
         }
 
         /// Change the bus configuration.
-        // FIXME: when https://github.com/esp-rs/esp-hal/issues/2839 is resolved, add an appropriate `# Error` entry.
+        ///
+        /// # Errors.
+        /// If frequency passed in config exceeds
```
Comment (SergioGasquez) [inline esp-hal/src/spi/master.rs:1598]:
```suggestion
        /// # Errors
        ///
        /// If frequency passed in config exceeds
```

File: esp-hal/src/spi/master.rs [hunk 12]
```diff
@@ -2017,7 +2062,13 @@ mod dma {
...
```
Comment (SergioGasquez) [inline esp-hal/src/spi/master.rs:2067]:
```suggestion
        /// # Errors
        ///
        /// If frequency passed in config exceeds
```

File: esp-hal/src/uart.rs [hunk 13]
```diff
@@ -739,7 +787,18 @@ where
     /// Change the configuration.
     ///
     /// Note that this also changes the configuration of the TX half.
-    // FIXME: when https://github.com/esp-rs/esp-hal/issues/2839 is resolved, add an appropriate `# Error` entry.
+    ///
+    /// # Errors
+    /// [`ConfigError::UnsupportedFifoThreshold`] will be returned if the RX
```
Comment (SergioGasquez) [inline esp-hal/src/uart.rs:792]:
```suggestion
    /// # Errors
    ///
    /// [`ConfigError::UnsupportedFifoThreshold`] will be returned if the RX
```

File: esp-hal/src/uart.rs [hunk 14]
```diff
@@ -974,7 +1033,9 @@ impl<'d> Uart<'d, Blocking> {
     /// # Ok(())
     /// # }
     /// ```
-    // FIXME: when https://github.com/esp-rs/esp-hal/issues/2839 is resolved, add an appropriate `# Error` entry.
+    /// 
+    /// # Errors
+    /// See [`Uart::apply_config`].
```
Comment (SergioGasquez) [inline esp-hal/src/uart.rs:1038]:
```suggestion
    /// # Errors
    ///
    /// See [`Uart::apply_config`].
```

File: esp-hal/src/uart.rs [hunk 15]
```diff
@@ -1165,7 +1226,15 @@ where
     }
 
     /// Change the configuration.
-    // FIXME: when https://github.com/esp-rs/esp-hal/issues/2839 is resolved, add an appropriate `# Error` entry.
+    ///
+    /// # Errors.
+    /// [`ConfigError::UnsupportedFifoThreshold`] will be returned in the cases
```
Comment (SergioGasquez) [inline esp-hal/src/uart.rs:1231]:
```suggestion
    /// # Errors
    ///
    /// [`ConfigError::UnsupportedFifoThreshold`] will be returned in the cases
```

File: esp-hal/src/uart.rs [hunk 16]
```diff
@@ -2547,6 +2629,51 @@ impl Info {
         txfifo_rst(self.regs(), true);
         txfifo_rst(self.regs(), false);
     }
+
+    fn verify_baudrate(&self, clk: u32, config: &Config) -> Result<(), ConfigError> {
+        // taken from https://github.com/espressif/esp-idf/blob/master/components/hal/esp32c6/include/hal/uart_ll.h#L433-L444
```
Comment (SergioGasquez) [inline esp-hal/src/uart.rs:2634]: We should use a commit instead of master for the link

**Review by SergioGasquez — COMMENTED** [review]
Some formatting nitpicks

File: esp-hal/src/uart.rs (hunk 16 above)
Comment (jessebraham) [reply esp-hal/src/uart.rs:2634]: Yeah linking to specific lines without a commit hash is just a recipe for future confusion

Comment (playfulFence) [reply esp-hal/src/uart.rs:2634]: Agreed

**Review by SergioGasquez — APPROVED** [review]

File: esp-hal/src/uart.rs [hunk 17]
```diff
@@ -455,6 +494,10 @@ pub struct UartRx<'d, Dm> {
 #[cfg_attr(feature = "defmt", derive(defmt::Format))]
 #[non_exhaustive]
 pub enum ConfigError {
+    /// The requested baud rate is not achievable.
+    UnachievableBaudrate,
```
Comment (MabezDev) [inline esp-hal/src/uart.rs:498]: I forget if we can mark enum variants as unstable (cc: @bugadani) but as this is related to the unstable tolerance stuff, we should also mark this as unstable?

File: esp-hal/src/uart.rs [hunk 18]
```diff
@@ -739,7 +787,19 @@ where
     /// Change the configuration.
     ///
     /// Note that this also changes the configuration of the TX half.
-    // FIXME: when https://github.com/esp-rs/esp-hal/issues/2839 is resolved, add an appropriate `# Error` entry.
+    ///
+    /// # Errors
+    ///
+    /// [`ConfigError::UnsupportedFifoThreshold`] will be returned if the RX
+    /// FIFO threshold passed in `Config` exceeds the maximum value (
```
Comment (MabezDev) [inline esp-hal/src/uart.rs:794]: Similar to my other comment, I'd avoid writing the conditions in long sentences when an error variant has more than one return condition, I think bullet pointing it should be clearer.

File: hil-test/tests/uart.rs [hunk 19]
```diff
@@ -43,6 +43,35 @@ mod tests {
...
+                    .with_baudrate_tolerance(uart::BaudrateTolerance::ErrorPercent(10)),
+            )
+            .unwrap();
+
+        ctx.uart.write_bytes(&[0x42]).unwrap();
+        let mut byte = [0u8; 1];
+        ctx.uart.read_bytes(&mut byte).unwrap();
+        assert_eq!(byte[0], 0x42);
+    }
+
```
Comment (MabezDev) [inline hil-test/tests/uart.rs:74]: I can't comment on the diff, but could you add some more tests to `test_send_receive_different_baud_rates_and_clock_sources` to go up to the full 5Mbaud (and maybe some intervals in between)?

**Review by MabezDev — CHANGES_REQUESTED** [review]
Thank you! This is looking good, most of my comments are related to the wording or layout, the validation code itself is looking solid!

File: esp-hal/src/uart.rs [hunk 20]
```diff
@@ -1165,7 +1226,15 @@ where
     }
 
     /// Change the configuration.
-    // FIXME: when https://github.com/esp-rs/esp-hal/issues/2839 is resolved, add an appropriate `# Error` entry.
+    ///
+    /// # Errors.
+    /// [`ConfigError::UnsupportedFifoThreshold`] will be returned in the cases
+    /// described in [`UartRx::apply_config`] and
+    /// [`ConfigError::UnsupportedBaudrate`] if baud rate passed in config
```
[the remark this answers is not in the document]
Comment (MabezDev) [reply esp-hal/src/uart.rs:1236]: Oh and please remove the period in the `# Errors` heading.

File: esp-hal/src/uart.rs [hunk 21]
```diff
@@ -2547,6 +2629,51 @@ impl Info {
...
+            } else { // esp32c6, esp32h2
+                let pcr = crate::peripherals::PCR::regs();
+                let sclk_div_num = pcr.uart0_sclk_conf().read().uart0_sclk_div_num().bits() as u32;
+                let actual_baud = (clk << 4) / ((((clkdiv as u32) << 4) | clkdiv_frag) * (sclk_div_num + 1));
+            }
+        };
+
+        match config.baudrate_tolerance {
+            BaudrateTolerance::Exact => {
+                let deviation = ((config.baudrate as i64 - actual_baud as i64).unsigned_abs()
```
[the remark this answers is not in the document]
Comment (playfulFence) [reply esp-hal/src/uart.rs:2613]: Can they? What if baudrate or actual_baud is greater than `i32::MAX`? Wouldn't it overflow?

File: esp-hal/src/uart.rs (hunk 17 above)
Comment (bugadani) [reply esp-hal/src/uart.rs:498]: It's impossible to mark enum variants as unstable. All we can do is cfg them away and return an Unknown/Other error instead.

File: esp-hal/src/uart.rs [hunk 22]
```diff
@@ -2547,6 +2629,51 @@ impl Info {
...
+        // (it's different for different chips)
+        let clkdiv_reg = self.regs().clkdiv().read();
+        let clkdiv_frag = clkdiv_reg.frag().bits() as u32;
+        let clkdiv = clkdiv_reg.clkdiv().bits();
+
+        cfg_if::cfg_if! {
+            if #[cfg(any(esp32, esp32s2))] {
+                let actual_baud = (clk << 4) / ((clkdiv << 4) | clkdiv_frag);
+            } else if #[cfg(any(esp32c2, esp32c3, esp32s3))] {
+                let sclk_div_num = self.regs().clk_conf().read().sclk_div_num().bits() as u32;
```
[the remark this answers is not in the document]
Comment (playfulFence) [reply esp-hal/src/uart.rs:2597]: Good catch, but I think in this specific case it will actually only add new lines 🤔

File: esp-hal/src/uart.rs (hunk 21 above)
[the remark this answers is not in the document]
Comment (MabezDev) [reply esp-hal/src/uart.rs:2613]: `i32::MAX` is over 2 billion, our max supported baud is 5 million, even if a new chip comes out which could do 500million baud, we have plenty of room in a `i32`.

File: esp-hal/src/uart.rs (hunk 22 above)
[the remark this answers is not in the document]
Comment (MabezDev) [reply esp-hal/src/uart.rs:2597]: yeah, ignore this one I think, it's cleaner to dupe here

File: esp-hal/src/uart.rs (hunk 21 above)
[the remark this answers is not in the document]
Comment (bugadani) [reply esp-hal/src/uart.rs:2613]: 2GHz UART wen

File: esp-hal/src/uart.rs (hunk 17 above)
Comment (MabezDev) [reply esp-hal/src/uart.rs:498]: Gotcha so we can do what we do for spi dma error: https://github.com/MabezDev/esp-hal/blob/2ff28b14b58d3d726aafc0456143e5022b06f0e6/esp-hal/src/spi/mod.rs#L26-L28

and in `verify_baudrate` we can cfg away the `match config.baudrate_tolerance {` when unstable isn't enabled.

**Review by MabezDev — APPROVED** [review]
LGTM, thanks!
