### PR TITLE
Fix S3-PSRAM mapping with later bootloaders

### LINKED ISSUE #3619: ESP32-S3: PSRAM stopps working when using a more up-to-date esp-idf bootloader
e.g. `cargo xtask run example qa-test esp32s3 --example=psram` works fine with the bootloader currently shipping with espflash v.3.3.0 but stops working with the updated bootloaders on espflash's main

This is the case for both "quad" and "octal" SPI RAM

Note: It's still working fine for ESP32 and ESP32-S2

### PR DESCRIPTION
**Pull request by bjoernQ**
## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [ ] I have updated existing examples or added new ones (if applicable).
- [x] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [x] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [ ] I have added necessary changes to user code to the [Migration Guide](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/MIGRATING-0.21.md).
- [x] My changes are in accordance to the [esp-rs developer guidelines](https://github.com/esp-rs/esp-hal/blob/main/documentation/DEVELOPER-GUIDELINES.md)

#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/documentation/CONTRIBUTING.md) and followed its instructions.

#### Description

Fixes #3619

#### Testing
Run the psram qa-test with a recent bootloader (e.g. use a recent commit of espflash)

### CODE REVIEW

**Comment by bjoernQ** [comment]
Once we update the bootloader used by the hil-tests we will also check this in CI

File: esp-hal/src/soc/esp32s3/psram.rs [hunk 1]
```diff
@@ -179,7 +179,10 @@ pub(crate) fn init_psram(config: PsramConfig) {
         // https://docs.espressif.com/projects/esp-idf/en/stable/esp32s3/api-reference/system/mm.html#introduction
         let mmu_table_ptr = DR_REG_MMU_TABLE as *const u32;
         let mut mapped_pages = 0;
-        for i in (0..FLASH_MMU_TABLE_SIZE).rev() {
+
+        // the bootloader is using the last page to access flash internally
+        // (e.g. to read the app descriptor) so we just skip that
+        for i in (0..(FLASH_MMU_TABLE_SIZE - 1)).rev() {
```
Comment (Dominaezzz) [inline esp-hal/src/soc/esp32s3/psram.rs:185]: This logic is hard coded for the esp-idf bootloader, should it go behind a feature/config?

Comment (bjoernQ) [reply esp-hal/src/soc/esp32s3/psram.rs:185]: In theory probably yes - but I'm not sure it will have any real-world implications 🤔

**Review by JurajSadel — APPROVED** [review]
Thanks!

File: esp-hal/src/soc/esp32s3/psram.rs (hunk 1 above)
Comment (bugadani) [reply esp-hal/src/soc/esp32s3/psram.rs:185]: Ideally this code would be in the bootloader support crate anyway, so I don't think we should further complicate this for now.

File: esp-hal/src/soc/esp32s3/psram.rs [hunk 2]
```diff
@@ -214,7 +217,7 @@ pub(crate) fn init_psram(config: PsramConfig) {
             0,
         ) != 0
         {
-            panic!("cache_dbus_mmu_set failed");
+            //   panic!("cache_dbus_mmu_set failed");
```
Comment (bugadani) [inline esp-hal/src/soc/esp32s3/psram.rs]: Why was this removed?

Comment (bjoernQ) [reply esp-hal/src/soc/esp32s3/psram.rs]: thanks for pointing this out - forgot about this commented out line

**Review by bugadani — APPROVED** [review]
