### PR TITLE
Split ElevatedRunLevel out of Priority

### LINKED ISSUE #5145: RunLevel::current() panics with InvalidInterruptPriority at Xtensa interrupt level > 3
## Bug description

`RunLevel::current()` panics with `InvalidInterruptPriority` at startup when WiFi/BT coexistence is enabled. The coex firmware calls back into `is_in_isr()` while running at Xtensa interrupt level 4–5, causing `Priority::try_from_u32` to receive a value greater than 3 and panic.

Note: there is an existing `TODO` in the `Priority` enum acknowledging that higher priority levels are not yet represented.

Introduced by commit `7895863` ("Remove interrupts-disabled check #5103").

```
[ERROR] panicked at 'unwrap failed: RunLevel :: try_from_u32(xtensa_lx :: interrupt :: get_level())'
error: `InvalidInterruptPriority` (esp_hal src/interrupt/xtensa.rs:236)
[ERROR]  (esp_backtrace esp-backtrace/src/lib.rs:80)
[ERROR] ====================== PANIC ====================== (esp_backtrace esp-backtrace/src/lib.rs:80)
[ERROR] panicked at /Users/eschaal/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/defmt-1.0.1/src/lib.rs:385:5 (esp_backtrace esp-backtrace/src/lib.rs:80)
[ERROR]  (esp_backtrace esp-backtrace/src/lib.rs:80)
[ERROR] Backtrace: (esp_backtrace esp-backtrace/src/lib.rs:80)
[ERROR]  (esp_backtrace esp-backtrace/src/lib.rs:80)
[ERROR] 0x422b252e (esp_backtrace esp-backtrace/src/lib.rs:80)
0x422b252e - core::panicking::panic_fmt
    at /Users/eschaal/.rustup/toolchains/esp/lib/rustlib/src/rust/library/core/src/panicking.rs:80                                                                                                                                       
[ERROR] 0x422b2516 (esp_backtrace esp-backtrace/src/lib.rs:80)                                                                                                                                                                           
0x422b2516 - core::panicking::panic
    at /Users/eschaal/.rustup/toolchains/esp/lib/rustlib/src/rust/library/core/src/panicking.rs:150                                                                                                                                      
[ERROR] 0x422aedee (esp_backtrace esp-backtrace/src/lib.rs:80)                                                                                                                                                                           
0x422aedee - __defmt_default_panic
    at /Users/eschaal/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/defmt-1.0.1/src/lib.rs:385                                                                                                                                    
[ERROR] 0x42297fb7 (esp_backtrace esp-backtrace/src/lib.rs:80)                                                                                                                                                                           
0x42297fb7 - defmt::export::panic
    at /Users/eschaal/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/defmt-1.0.1/src/export/mod.rs:133                                                                                                                             
[ERROR] 0x40378dab (esp_backtrace esp-backtrace/src/lib.rs:80)                                                                                                                                                                           
0x40378dab - esp_hal::interrupt::RunLevel::current
    at /Users/eschaal/src/github.com/esp-hal/esp-hal/src/interrupt/mod.rs:422                                                                                                                                                            
[ERROR] 0x422cbf49 (esp_backtrace esp-backtrace/src/lib.rs:80)                                                                                                                                                                           
[ERROR] 0x422cc097 (esp_backtrace esp-backtrace/src/lib.rs:80)
0x422cc097 - coex_core_pre_init
    at ??:??                                                                                                                                                                                                                             
[ERROR] 0x422cbedc (esp_backtrace esp-backtrace/src/lib.rs:80)                                                                                                                                                                           
0x422cbedc - coex_pre_init
    at ??:??                                                                                                                                                                                                                             
[ERROR] 0x42277402 (esp_backtrace esp-backtrace/src/lib.rs:80)                                                                                                                                                                           
0x42277402 - esp_radio::wifi::coex_initialize
    at /Users/eschaal/src/github.com/esp-hal/esp-radio/src/wifi/mod.rs:966                                                                                                                                                               
[ERROR] 0x42278870 (esp_backtrace esp-backtrace/src/lib.rs:80)                                                                                                                                                                           
0x42278870 - esp_radio::init
    at /Users/eschaal/src/github.com/esp-hal/esp-radio/src/lib.rs:310                                                                                                                                                                    
[ERROR]  (esp_backtrace esp-backtrace/src/lib.rs:80)                                                                                                                                                                                     
[ERROR]  (esp_backtrace esp-backtrace/src/lib.rs:80)
[ERROR]  (esp_backtrace esp-backtrace/src/lib.rs:80)
```

## To Reproduce

1. Enable WiFi + BT coexistence on an ESP32/ESP32-S2/ESP32-S3 target.
2. Initialize the radio stack (esp-radio).
3. Observe panic at startup during `coex_core_pre_init`.

## Expected behavior

No panic.

## Environment

- Target device: ESP32, ESP32-S2, ESP32-S3 (Xtensa)
- Crate name and version: esp-hal (main), esp-radio (main)

### PR DESCRIPTION
**Pull request by bugadani**
Fixes #5145 and enables coex on the radio tests which previously would have failed and caught the issue. The PR also fixes another issue discovered during implementation: on ESP32 we can't call `coex_deinit` in an interrupt-free context.

I **think** this issue has been introduced by https://github.com/esp-rs/esp-hal/pull/4482 so no changelog entry should be necessary.

### CODE REVIEW

File: esp-hal/src/interrupt/mod.rs [hunk 1]
```diff
@@ -400,7 +400,7 @@ pub enum RunLevel {
     ThreadMode,
 
     /// An elevated level, usually an interrupt handler's.
-    Interrupt(Priority),
+    Interrupt(ElevatedRunLevel),
```
Comment (MabezDev) [inline esp-hal/src/interrupt/mod.rs:403]: Maybe the enum variant itself should be `Elevated` as this covers all the other possibles, like in an exception?

Comment (bugadani) [reply esp-hal/src/interrupt/mod.rs:403]: I'd like to reserve the possibility of having both Interrupt and Elevated. They aren't the same state - you can elevate the run level outside of interrupt handlers, too.

File: esp-radio/src/lib.rs [hunk 2]
```diff
@@ -340,34 +338,80 @@ pub(crate) fn deinit() {
...
+                    } else {
+                        Operation::Nothing
+                    }
+                }
+            });
+
+            match op {
+                Operation::Spin => {}
+                Operation::CallFunction => {
+                    deinit();
```
Comment (bugadani) [inline esp-radio/src/lib.rs]: ESP32 fails to deinitialize (it prints a message and loops) if coex_deinit is called in an interrupt-free context.

File: esp-hal/src/interrupt/riscv.rs [hunk 3]
```diff
@@ -167,6 +167,26 @@ for_each_interrupt_priority!(
                 [$(Priority::$ident,)*].into_iter()
             }
         }
+
+        /// Interrupt run levels.
+        #[derive(Copy, Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
+        #[cfg_attr(feature = "defmt", derive(defmt::Format))]
+        #[repr(u8)]
+        pub enum ElevatedRunLevel {
```
Comment (MabezDev) [inline esp-hal/src/interrupt/riscv.rs:175]: I understand why we're doing this, but will this always be a dupicate of `Priority` on Riscv? Would there be any new variants added to this, maybe relating to exceptions here, or not?

Should this be non_exhaustive regardless of above?

Comment (bugadani) [reply esp-hal/src/interrupt/riscv.rs:175]: Priority is generally a subset of ElevatedRunLevel, but on RISC-V, this is pretty much always the same, because the architecture doesn't have the same limitation as Xtensa does (which boils down to EXCM, and the window overflow/underflow exceptions, btw).

On CLIC these are limited by the bits in `mnlbits` (3 -> 8 levels), but on the other interrupt controllers the interrupt priorities are emulated and rather arbitrary. Technically, we could set this to non_exhaustive but I don't see us supporting more than 16 interrupt priorities for the older chips, and it's hardware limited on the newer ones.

> Would there be any new variants added to this, maybe relating to exceptions here, or not?

I don't think so? If we want to distinguish between threadmode-with-modified-runlevel, interrupt mode, exception mode, or even user/machine modes, we'd just add a new variant to RunLevel.

Comment (MabezDev) [reply esp-hal/src/interrupt/riscv.rs:175]: > Technically, we could set this to non_exhaustive but I don't see us supporting more than 16 interrupt priorities for the older chips, and it's hardware limited on the newer ones.

Yeah, fair enough - let's leave it as is.
