### PR TITLE
Fix perma-unstable crate detection

### LINKED ISSUE #4403: release tooling accidently bumps permaunstable crates
## Bug description

`cargo xrelease plan esp-rom-sys` yielded a minor version bump instead of a patch release.

```json
{
      "package": "esp-rom-sys",
      "semver_checked": false,
      "current_version": "0.1.2",
      "new_version": "0.2.0",
      "tag_name": "esp-rom-sys-v0.2.0",
      "bump": "Minor"
    },
```

### PR DESCRIPTION
**Pull request by bugadani**
Closes #4403

### CODE REVIEW

File: xtask/src/commands/release/plan.rs [hunk 1]
```diff
@@ -137,7 +137,7 @@ pub fn plan(workspace: &Path, args: PlanArgs) -> Result<()> {
             } else {
                 let forever_unstable = if let Some(metadata) =
                     package_tomls[&package].espressif_metadata()
-                    && let Some(Item::Value(forever_unstable)) = metadata.get("forever_unstable")
+                    && let Some(Item::Value(forever_unstable)) = metadata.get("forever-unstable")
```
Comment (bjoernQ) [inline xtask/src/commands/release/plan.rs:140]: oh

**Review by bjoernQ — APPROVED** [review]
