### PR TITLE
Fix off-by-one

### LINKED ISSUE #3976: Incorrect bounds check in `read` implementation for `FlashRegion`
## Bug description

Trait `embedded_storage::ReadStorage` is implemented for `FlashRegion`. The `read` function do bounds check:
https://github.com/esp-rs/esp-hal/blob/54e9646fbdcabb7de238a7b4a3a02183101adf95/esp-bootloader-esp-idf/src/partitions.rs#L513-L519
https://github.com/esp-rs/esp-hal/blob/54e9646fbdcabb7de238a7b4a3a02183101adf95/esp-bootloader-esp-idf/src/partitions.rs#L499-L501

For what it seems to me, there is a off-by-one error in the upper bound check (miss `-1` in the value passed to `contains`).

## To Reproduce

Try to read exactly the size of the flash region.

## Expected behavior

No OutOfBounds error.

## Environment

- ESP32-S3
- 1.0.0-rc0

### PR DESCRIPTION
**Pull request by bjoernQ**
## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [ ] I have updated existing examples or added new ones (if applicable).
- [ ] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [ ] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [ ] I have added necessary changes to user code to the [Migration Guide](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/MIGRATING-0.21.md).
- [ ] My changes are in accordance to the [esp-rs developer guidelines](https://github.com/esp-rs/esp-hal/blob/main/documentation/DEVELOPER-GUIDELINES.md)

#### Extra:
- [ ] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/documentation/CONTRIBUTING.md) and followed its instructions.

#### Description
Fixes #3976

#### Testing
manual testing

### CODE REVIEW

**Review by MabezDev — COMMENTED** [review]
Maybe we should create a proper `Range` and use the `contains` method there, as I think this would have behaved properly in this case (the end value is exclusive, not inclusive)

File: esp-bootloader-esp-idf/src/partitions.rs [hunk 1]
```diff
@@ -493,11 +491,19 @@ impl<F> FlashRegion<'_, F> {
     pub fn partition_size(&self) -> usize {
         self.raw.len() as _
     }
+
+    fn range(&self) -> core::ops::RangeInclusive<u32> {
+        self.raw.offset()..=self.raw.offset() + self.raw.len()
```
Comment (bouttier) [inline esp-bootloader-esp-idf/src/partitions.rs]:
```suggestion
    fn range(&self) -> core::ops::Range<u32> {
        self.raw.offset()..self.raw.offset() + self.raw.len()
```
I think `self.raw.offset() + self.raw.len()` is not part of the partition.

File: esp-bootloader-esp-idf/src/partitions.rs [hunk 2]
```diff
@@ -493,11 +491,19 @@ impl<F> FlashRegion<'_, F> {
...
+    }
+
+    fn in_range(&self, start: u32, len: usize) -> bool {
+        self.range().contains(&start) && self.range().contains(&(start + len as u32))
```
Comment (bouttier) [inline esp-bootloader-esp-idf/src/partitions.rs]:
```suggestion
        self.range().contains(&start) && self.range().contains(&(start + len as u32 - 1))
```
It seems to me last address required to be in range is `start + len - 1`

**Review by bouttier — COMMENTED** [review]
Not sure of the effect with 0 length partition…

File: esp-bootloader-esp-idf/src/partitions.rs (hunk 2 above)
Comment (bjoernQ) [reply esp-bootloader-esp-idf/src/partitions.rs]: yes that would express the intend more clearly

File: esp-bootloader-esp-idf/src/partitions.rs [hunk 3]
```diff
@@ -493,11 +491,19 @@ impl<F> FlashRegion<'_, F> {
     pub fn partition_size(&self) -> usize {
         self.raw.len() as _
     }
+
+    fn range(&self) -> core::ops::Range<u32> {
+        self.raw.offset()..self.raw.offset() + self.raw.len()
+    }
+
+    fn in_range(&self, start: u32, len: usize) -> bool {
+        self.range().contains(&start) && self.range().contains(&(start + len as u32 - 1))
```
Comment (bugadani) [inline esp-bootloader-esp-idf/src/partitions.rs]:
```suggestion
        self.range().contains(&start) && (start + len as u32 <= self.range().end)
```

Comment (bjoernQ) [reply esp-bootloader-esp-idf/src/partitions.rs]: looking forward to the new Range API getting stabilized one day :)
