### PR TITLE
ESP32/ESP32-S2: I2C Workaround

### LINKED ISSUE #3167: Frequent I2C timeouts when running I2C alongside WiFi stack
## Bug description

Bug was seen when driving a display with a flush mechanism (full screen redraw) at the same time as running the WiFi stack on ProS3. If the WiFi is not running, I2C timeouts are not seen.

## To Reproduce

Bug was observed on a ProS3 connected via I2C to an Adafruit FeatherWing display. The display driver used was https://github.com/aaron-hardin/sh1107
1. Connect display to 4-pin connector for I2C on the ProS3
2. Flash code which spins up the WiFi stack and also updates the display at regular intervals (e.g. 10 Hz)
3. Print I2C errors to trace
4. Observe regular timeouts, also visual glitches on the display

Minimal examples of the timeouts being caused by WiFi and by `defmt` are [in this comment](https://github.com/esp-rs/esp-hal/issues/3167#issuecomment-2679152475)

## Expected behavior

No I2C timeouts caused by running alongside WiFi.

## Environment

- Target device: ProS3
- Crate name and version: esp-hal 0.23.1

### LINKED ISSUE #3178: I2C timeouts reading ublox gps
## Bug description

I have a Sparkfun SAM-M10Q GPS module which outputs NMEA sentences on i2c port. The output is around 1Kbytes per second. When I read the data to a buffer of size 32 or more bytes, I only get timeouts. When I keep the buffer size 31, it works.

Probably related to #3034 and/or #3167.

## To Reproduce

```rust
#![no_std]
#![no_main]

use esp_backtrace as _;
use esp_hal::{
    delay::Delay,
    i2c::master::{BusTimeout, Config, I2c},
    main,
};
use esp_println::{print, println};

const DATA_BUF_SIZE: usize = 32;

#[main]
fn main() -> ! {
    let peripherals = esp_hal::init(esp_hal::Config::default());
    let delay = Delay::new();
    let mut i2c = I2c::new(
        peripherals.I2C0,
        Config::default().with_timeout(BusTimeout::Maximum),
    )
    .unwrap()
    .with_sda(peripherals.GPIO16)
    .with_scl(peripherals.GPIO17);

    loop {
        let mut size_buf = [0u8; 2];
        let mut data_buf = [0u8; DATA_BUF_SIZE];
        match i2c.write_read(0x42, &[0xfd], &mut size_buf) {
            Ok(_) => {}
            Err(err) => {
                println!("Error reading the size {:?}", err);
                delay.delay_millis(500);
                continue;
            }
        };
        let size: usize = ((size_buf[0] as u16) << 8 | (size_buf[1] as u16)).into();

        let mut remaining = size;
        println!(
            "Got size_buf {:?}: size:{:?}",
            size_buf, remaining
        );

        while remaining > 0 {
            let bytes_to_read = if remaining > DATA_BUF_SIZE {
                DATA_BUF_SIZE
            } else {
                remaining
            };

            match i2c.write_read(0x42, &[0xff], &mut data_buf[0..bytes_to_read]) {
                Ok(_) => {}
                Err(err) => {
                    println!("Error reading data: {:?}", err);
                    break;
                }
            }
            remaining -= bytes_to_read;
            print!("{}", core::str::from_utf8(&data_buf).unwrap());
        }
        println!("Finished reading GPS data");
        println!("");
        delay.delay_millis(500);
    }
}
```
For `DATA_BUF_SIZE` > 31, I just get timeouts.
```
Got size_buf [0, 0]: size:0
Finished reading GPS data

Got size_buf [5, 8]: size:1288
Error reading data: Timeout
Finished reading GPS data

Got size_buf [9, 239]: size:2543
Error reading data: Timeout
Finished reading GPS data

Got size_buf [19, 222]: size:5086
Error reading data: Timeout
Finished reading GPS data

```
For `DATA_BUF_SIZE=31` everything works as expected.

## Expected behavior

Reading into a large buffer should output the same result as a smaller buffer.

Here is the output with the buffer size 31:
```
Got size_buf [0, 0]: size:0
Finished reading GPS data

Got size_buf [4, 252]: size:1276
$GNRMC,181453.00,A,3406.41996,N,02306.00679,E,0.009,,250225,,,D,V*1F
$GNVTG,,T,,M,0.009,N,0.017,K,D*37
$GNGGA,181453.00,3406.41996,N,02306.00679,E,2,12,0.62,2.3,M,48.4,M,,*4A
$GNGSA,A,3,27,01,14,08,10,02,32,,,,,,1.14,0.62,0.96,1*05
$GNGSA,A,3,68,82,67,83,,,,,,,,,1.14,0.62,0.96,2*03
$GNGSA,A,3,36,09,25,34,04,02,06,11,30,,,,1.14,0.62,0.96,3*03
$GNGSA,A,3,20,30,41,32,,,,,,,,,1.14,0.62,0.96,4*0E
$GNGSA,A,3,,,,,,,,,,,,,1.14,0.62,0.96,5*0A
$GPGSV,3,1,12,01,40,275,32,02,52,291,28,03,14,215,22,08,84,185,37,1*68
$GPGSV,3,2,12,10,41,049,34,14,13,320,23,16,05,177,19,27,48,135,40,1*6E
$GPGSV,3,3,12,32,30,103,30,36,33,142,41,40,19,118,32,49,40,177,31,1*6C
$GPGSV,1,1,01,23,01,042,,0*52
$GLGSV,2,1,06,67,39,050,23,68,49,125,32,73,20,243,18,75,09,340,15,1*74
$GLGSV,2,2,06,82,28,082,31,83,58,036,26,1*71
$GLGSV,1,1,03,69,15,170,,74,27,291,,84,29,302,,0*4D
$GAGSV,3,1,11,02,42,223,30,04,19,055,20,05,07,157,19,06,26,082,29,7*71
$GAGSV,3,2,11,09,26,108,34,10,00,076,08,11,24,070,34,25,09,179,18,7*77
$GAGSV,3,3,11,30,36,295,28,34,44,278,19,36,69,026,33,7*4D
$GAGSV,1,1,01,27,02,332,,0*40
$GBGSV,2,1,06,20,16,187,,30,79,002,,32,55,133,,36,13,245,,0*72
$GBGSV,2,2,06,36,13,245,,41,34,053,,0*71
$GQGSV,1,1,00,0*64
$GNGLL,3406.41996,N,02306.00679,E,181453.00,A,D*77
2316.02679,E,181453.00,A,DFinished reading GPS data

Got size_buf [4, 252]: size:1276
$GNRMC,181454.00,A,3406.41996,N,02306.00688,E,0.114,,250225,,,D,V*1B
$GNVTG,,T,,M,0.114,N,0.211,K,D*3E
$GNGGA,181454.00,3406.41996,N,02306.00688,E,2,12,0.58,2.4,M,48.4,M,,*4D
$GNGSA,A,3,27,01,14,08,10,02,32,,,,,,1.08,0.58,0.92,1*05
$GNGSA,A,3,68,82,67,83,,,,,,,,,1.08,0.58,0.92,2*03
$GNGSA,A,3,36,09,25,34,04,02,06,11,30,,,,1.08,0.58,0.92,3*03
$GNGSA,A,3,20,30,41,32,,,,,,,,,1.08,0.58,0.92,4*0E
$GNGSA,A,3,,,,,,,,,,,,,1.08,0.58,0.92,5*0A
$GPGSV,3,1,12,01,40,275,32,02,52,291,27,03,14,215,22,08,84,185,36,1*66
$GPGSV,3,2,12,10,41,049,41,14,13,320,22,16,05,177,19,27,48,135,41,1*6C
$GPGSV,3,3,12,32,30,103,23,36,33,142,40,40,19,118,31,49,40,177,31,1*6C
$GPGSV,1,1,01,23,01,042,,0*52
$GLGSV,2,1,06,67,39,050,28,68,49,125,31,73,20,243,20,75,09,340,18,1*7A
$GLGSV,2,2,06,82,28,082,31,83,58,036,26,1*71
$GLGSV,1,1,03,69,15,170,,74,27,291,,84,29,302,,0*4D
$GAGSV,3,1,11,02,42,223,29,04,19,055,23,05,07,157,22,06,26,082,31,7*7B
$GAGSV,3,2,11,09,26,108,34,10,00,076,07,11,24,070,35,25,09,179,21,7*73
$GAGSV,3,3,11,30,36,295,28,34,44,278,23,36,69,026,33,7*44
$GAGSV,1,1,01,27,02,332,,0*40
$GBGSV,2,1,06,20,16,187,,30,79,002,,32,55,133,,36,13,245,,0*72
$GBGSV,2,2,06,36,13,245,,41,34,053,,0*71
$GQGSV,1,1,00,0*64
$GNGLL,3406.41996,N,02306.00688,E,181454.00,A,D*7E
2306.00688,E,181454.00,A,DFinished reading GPS data

Got size_buf [0, 0]: size:0
Finished reading GPS data
```

## Environment

- Target device: esp32 (revision v1.0)
- Crate name and version: esp-hal 0.23.1

### PR DESCRIPTION
**Pull request by bjoernQ**
## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [ ] I have updated existing examples or added new ones (if applicable).
- [x] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [x] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [ ] I have added necessary changes to user code to the [Migration Guide](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/MIGRATING-0.21.md).
- [x] My changes are in accordance to the [esp-rs API guidelines](https://github.com/esp-rs/esp-hal/blob/main/documentation/API-GUIDELINES.md)

#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/documentation/CONTRIBUTING.md) and followed its instructions.

#### Description
Fixes #3178 
Fixes #3167

Basically, this does three things
- don't combine STOP with other commands
- try to place END at the same index during a `write`, `read` and `write_read`
- don't use FIFO wrapping (to prevent timing issues)

I don't see how to guarantee things will always work for a custom `transaction` on ESP32/ESP32-S2 - so I added some docs

#### Testing
I used an VL53L5 sensor (which requires large (32k) writes and reads (a few hundred bytes). Additionally, I tested with a bit-banged I2C slave ( https://github.com/bjoernQ/i2c-dummy-device )

### CODE REVIEW

**Comment by bugadani** [comment]
We need a test case in the HIL tester that fails without this PR.

File: hil-test/tests/i2c.rs [hunk 1]
```diff
@@ -71,7 +71,7 @@ mod tests {
             }
         }
 
-        assert_eq!(ctx.i2c.write(DUT_ADDRESS, &[]), Ok(()));
+        assert_eq!(ctx.i2c.write(DUT_ADDRESS, &[0xaa]), Ok(()));
```
Comment (bugadani) [inline hil-test/tests/i2c.rs:74]: This is wrong, we need to support 0-byte writes

Comment (bjoernQ) [reply hil-test/tests/i2c.rs:74]: ah - yeah now I see it was not always a no-op apparently

File: esp-hal/src/i2c/master/mod.rs [hunk 2]
```diff
@@ -1683,24 +1695,84 @@ impl Driver<'_> {
...
-            // WRITE command
-            add_cmd(
-                cmd_iterator,
-                Command::Write {
-                    ack_exp: Ack::Ack,
-                    ack_check_en: true,
-                    length: write_len as u8,
-                },
-            )?;
+            cfg_if::cfg_if! {
```
[the remark this answers is not in the document]
Comment (bjoernQ) [reply esp-hal/src/i2c/master/mod.rs:1714]: I tried it but while the call-site looks obviously better it makes the overall flow a bit harder to read - so I'm still undecided :)

**Comment by bjoernQ** [comment]
> We need a test case in the HIL tester that fails without this PR.

As said we can't with the BMP180 - one thing we _could_ do it artificially reduce the FIFO size for the test to force the error (maybe) - not sure if that is something we really want - if we want it, we could make the FIFO size user-configurable

**Comment by Dominaezzz** [comment]
> we can't with the BMP180

In case y'all decide to add another i2c slave, I vote for a gpio expander, as it can be validated with other peripherals (Like RMT, SPI slave, pcnt, etc)

**Comment by bugadani** [comment]
Probably fixes https://github.com/esp-rs/esp-hal/issues/3060

**Review by MabezDev — APPROVED** [review]
LGTM, thank you!

re hil test: I think we definitely want one here, we don't want to debug this again :D, but I suggest that we can merge this and open an issue for adding the test once the hardware arrives.

File: esp-hal/src/i2c/master/mod.rs [hunk 3]
```diff
@@ -2415,8 +2587,13 @@ impl Driver<'_> {
         if buffer.is_empty() {
             return self.write_operation_blocking(address, &[], start, stop);
         }
-        let chunk_count = buffer.len().div_ceil(I2C_CHUNK_SIZE);
-        for (idx, chunk) in buffer.chunks(I2C_CHUNK_SIZE).enumerate() {
+        let chunk_size = if buffer.len() % I2C_CHUNK_SIZE < 2 {
```
Comment (yalcinozhabes) [inline esp-hal/src/i2c/master/mod.rs:2617]: What's the logic here? Are you trying to avoid having a single byte chunk at the end? Because if so, it's still possible. For `esp32`, `chunk_size` is either 31 or 29. If the buffer length is slightly longer than 31 * 29 = 899, the last chunk will be the same size for each `chunk_size`. Indeed I am hitting timeouts when the buffer length is 900 and 901.

For me on `esp32` I am hitting timeouts with certain buffer sizes when the last chunk is of size is 2. So any buffer length in the set {31, 64, 95, 126 ...}, I cannot finish the read (the last chunk times out).

Comment (bjoernQ) [reply esp-hal/src/i2c/master/mod.rs:2617]: True - this needs to get fixed

Comment (bjoernQ) [reply esp-hal/src/i2c/master/mod.rs:2617]: But the good news it's that the general way to handle it is fine

**Review by bugadani — APPROVED** [review]
