### PR TITLE
Use syslog related functions from libprintf.a

### LINKED ISSUE #5113: print-logs-from-driver not longer works, and crashes with an exception
## Bug description

https://github.com/esp-rs/esp-wifi-sys/pull/497#issuecomment-3997269811

## To Reproduce

Run the new wifi_syslog qa test

## Environment

- Target device: Any Xtensa device
- Crate name and version: main

### PR DESCRIPTION
**Pull request by bjoernQ**
Fixes #5113

### CODE REVIEW

File: esp-radio/src/wifi/internal.rs [hunk 1]
```diff
@@ -13,6 +13,12 @@ use crate::{
     },
 };
 
+#[cfg(feature = "print-logs-from-driver")]
+unsafe extern "C" {
+    pub unsafe fn __esp_radio_log_write();
+    pub unsafe fn __esp_radio_log_writev();
```
Comment (bugadani) [inline esp-radio/src/wifi/internal.rs]: Could we declare these with the right signature so we don't have to transmute for no reason?

Comment (bjoernQ) [reply esp-radio/src/wifi/internal.rs]: then we would need nightly - just for that

Comment (bjoernQ) [reply esp-radio/src/wifi/internal.rs]: or maybe not - will check
