### PR TITLE
Fix DMA not having data available in time

### LINKED ISSUE #2440: Debug and re-enable I2S tests on ESP32
Disabled in #2439 due to noise.

### LINKED ISSUE #2909: ESP32 async SPI operatons time out

### PR DESCRIPTION
**Pull request by bugadani**
Fixes #2909

If anyone wants to check if this helps with #2863 I'd be grateful.

I bumped clocks to their max in tests to give the DMA less chance of randomly working.

The ESP32 registers were less than well described in the TRM, but other chips had enough hints.

### CODE REVIEW

File: esp-hal/src/dma/gdma.rs [hunk 1]
```diff
@@ -170,6 +170,29 @@ impl RegisterAccess for AnyGdmaTxChannel {
...
+            } else {
+                while self
+                    .ch()
+                    .outfifo_status()
+                    .read()
+                    .outfifo_empty()
+                    .bit_is_set()
+                {}
+            }
+        }
```
Comment (Dominaezzz) [inline esp-hal/src/dma/gdma.rs:195]: Rather than hijack the `start` method here, could this be a `TxRegisterAccess::is_fifo_empty()` then the loop can live in `ChannelTx::start_transfer`.

File: hil-test/tests/spi_half_duplex_write_psram.rs [hunk 2]
```diff
@@ -51,7 +51,9 @@ mod tests {
 
     #[init]
     fn init() -> Context {
-        let peripherals = esp_hal::init(esp_hal::Config::default());
+        let peripherals = esp_hal::init(
+            esp_hal::Config::default().with_cpu_clock(esp_hal::clock::CpuClock::max()),
```
[the remark this answers is not in the document]
Comment (bugadani) [reply hil-test/tests/spi_half_duplex_write_psram.rs:55]: Not really, but there's no point here

File: esp-hal/src/dma/gdma.rs (hunk 1 above)
Comment (bugadani) [reply esp-hal/src/dma/gdma.rs:195]: If we'd strip this out (which comes at a cost - we have to remember to call that function), we might as well expose it to the peripheral drivers and let them wait at the last possible moment. Right now, however, I prefer the safety of the current code.

**Comment by bugadani** [comment]
Speaking of things to forget, the i2s interrupt change needs a test

File: esp-hal/src/dma/gdma.rs (hunk 1 above)
Comment (Dominaezzz) [reply esp-hal/src/dma/gdma.rs:195]: > we have to remember to call that function

You only have to "remember" to do it here once right? https://github.com/esp-rs/esp-hal/blob/04ba779f2d41192ddd412a0d1bc35957889cb3a5/esp-hal/src/dma/mod.rs#L2311

I'm not sure what you mean

**Review by MabezDev — APPROVED** [review]
LGTM, thanks for the tests!

**Comment by Dominaezzz** [comment]
Oh I just realised, this will get stuck on empty DMA transfers right?

**Comment by bugadani** [comment]
Nope

**Comment by Dominaezzz** [comment]
Ohhhh you check for interrupts too, I missed that change sorry

**Review by Dominaezzz — APPROVED** [review]
