### PR TITLE
Do not reset `UsbSerialJtag` peripheral

### LINKED ISSUE #1954: UsbSerialJtag async breaks probe-rs on C6 on latest git
Hi! I update my project to latest git (to get embassy-executor match up) and my project now breaks debugging and flashing via probe-rs if I have enabled UsbSerialJtag.
This is what I get in probe-rs on first try (it flashes but after the program is running this happens:
```
 WARN probe_rs::session: Could not clear all hardware breakpoints: Probe(Usb(Custom { kind: Other, error: Stall }))
 WARN probe_rs::session: Failed to deconfigure device during shutdown: Probe(Usb(Custom { kind: Other, error: Stall }))
Error: An error with the usage of the probe occurred

Caused by:
    0: USB Communication Error
    1: endpoint STALL condition
  ```
This makes also the UsbSerial to stop outputting anything.
If I retry running probe-rs this is the output I get:
```
Error: Failed to open the debug probe.

Caused by:
    0: The debug probe could not be created.
    1: A USB error occurred.
    2: endpoint STALL condition
```
This worked fine before I updated esp-hal. And my project still works fine if I disable UsbSerialJtag.
To add that UsbSerial does work fine if I connect an already flashed project and do not run probe-rs, I get some hello world output.
Any idea what could cause that?

### PR DESCRIPTION
**Pull request by bugadani**
## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [x] I have updated existing examples or added new ones (if applicable).
- [x] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [x] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [x] My changes are in accordance to the [esp-rs API guidelines](https://github.com/esp-rs/esp-hal/blob/main/documentation/API-GUIDELINES.md)

#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/documentation/CONTRIBUTING.md) and followed its instructions.

#### Description

... doing so unfortunately kills the debugger connection, if done over USB.

We *might* want to detect if a debugger connection would use USB (i.e. the strapping pins, efuses and stars all align), but doing that is probably more complicated than what it's worth. Note that it's not the active connection that matters, but the possibility - resetting USB would prevent future connections.

#### Testing

Added a test and ran it on a C3, C6 and an S3.

Fixes #1954

cc @JurajSadel for the register name weirdness :)

### CODE REVIEW

**Comment by bugadani** [comment]
Note that if the added test fails, it will bring down the HIL tester. To fix that, we may need to cut USB power after a failed run.

File: esp-hal/src/debugger.rs [hunk 1]
```diff
@@ -0,0 +1,39 @@
+//! Debugger utilities
+
+/// Checks if a debugger is connected.
+pub fn debugger_connected() -> bool {
+    #[cfg(xtensa)]
+    {
```
Comment (MabezDev) [inline esp-hal/src/debugger.rs:6]: I think we should use method we have in `xtensa-lx` instead of duplicating the code here.

File: esp-hal/src/debugger.rs [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+            assist_debug
+                .core_0_debug_mode()
+                .read()
+                .core_0_debug_module_active()
+                .bit_is_set()
+        }
+        #[cfg(not(feature = "esp32c2"))]
+        {
+            assist_debug
+                .c0re_0_debug_mode()
```
Comment (MabezDev) [inline esp-hal/src/debugger.rs:28]: I opened https://github.com/esp-rs/esp-pacs/issues/269 so we can come back and clean this up later.

**Review by MabezDev — APPROVED** [review]
Other than the xtensa-lx comment, this LGTM

File: esp-hal/src/debugger.rs (hunk 1 above)
Comment (bugadani) [reply esp-hal/src/debugger.rs:6]: good call

**Review by JurajSadel — APPROVED** [review]
Thanks!
