### PR TITLE
Fix incorrect QSPI setup

### LINKED ISSUE #2229: `qspi_flash` example broken (at least on ESP32-S2 - most probably for all chips) since b5f0246
## Bug description

Since b5f0246

Output from the example is
```
[21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

While it should be
```
[48, 65, 6c, 6c, 6f, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff, ff]
Hello!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!................................................................
```

## To Reproduce

Run the `qspi_flash` example with an SPI flash chip attached

## Environment

Tested on ESP32-S2 but most probably broken for all chips.

(We should also make sure to improve our HIL-tests to catch this)

### PR DESCRIPTION
**Pull request by bugadani**
## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [x] I have updated existing examples or added new ones (if applicable).
- [x] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [x] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [x] I have added necessary changes to user code to the [Migration Guide](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/MIGRATING-0.21.md).
- [x] My changes are in accordance to the [esp-rs API guidelines](https://github.com/esp-rs/esp-hal/blob/main/documentation/API-GUIDELINES.md)

#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/documentation/CONTRIBUTING.md) and followed its instructions.

#### Description

Two-parter:
- QSPI setup was unfixed in #2198.
- We didn't support multi-line address without data. Similar issue in esp-idf: https://github.com/espressif/esp-idf/issues/5684

This fixes #2229 and adds test code to make sure we don't break QSPI again. This PR also works around an ESP32 limitation.

#### Testing

Observed behaviour change using a logic analyzer and also the changed test cases fail before the fix.

### CODE REVIEW

**Review by bjoernQ — COMMENTED** [review]
This actually fixes #2229 - weird given the result of the bisect and also manually checking that commit and the one before - Thanks!

**Comment by bugadani** [comment]
Awesome. The problem is, that the RX/TX swap introduced a buffer size issue and maybe your flash chip flashed the last 256 `!` characters that it received. So one problem was fixed by restoring the buffer sizes in #2139 but then I managed to break this again, later, which your bisect might have jumped over.

**Comment by bugadani** [comment]
I've been banging my head against ESP32 for a while now, and I think that chip simply can't do a 4-line address phase if it doesn't have data to transmit afterwards. The chip defaults back to 1-line address phase if `usr_miso` and `usr_mosi` are clear. I guess we could work around this by sending address as data if there is no data...

**Comment by Dominaezzz** [comment]
Just return an error if it's not supported I think.

**Comment by bugadani** [comment]
Why? It's supported everywhere else, users expect it to work and it's simple to work around.

**Comment by Dominaezzz** [comment]
It's not like all the SPI hardware on all chips works the same. Some have more features that others. It just so happens the ESP32 can't support this one case.

If users want it to "just work" everywhere, they should just use the data phase for everything themselves. Doing it secretly is too hacky imo.

**Comment by Dominaezzz** [comment]
Also, not all implementations of `DmaTxBuffer` will support the methods you just added.

**Comment by bugadani** [comment]
> It's not like all the SPI hardware on all chips works the same.

One of the jobs of the HAL is to equalize support as much as possible.

> Also, not all implementations of DmaTxBuffer will support the methods you just added.

Then they will be free to return an error.

**Comment by Dominaezzz** [comment]
> > Also, not all implementations of DmaTxBuffer will support the methods you just added.
> 
> Then they will be free to return an error.

How is that different from just returning an error upfront? User will still end up having to deal with it.

Also users won't be expecting their `DmaTxBuf`s to suddenly contain data they never added. If they put it in a loop, the first iteration would do the right thing, then the second iteration would send the address (in the address phase) + the previous address (in the data phase).

> > It's not like all the SPI hardware on all chips works the same.
> 
> One of the jobs of the HAL is to equalize support as much as possible.

Yeah but there should be a line somewhere I think.

**Comment by Dominaezzz** [comment]
There's the option of not using DMA and just using the CPU Buffer for the data phase. (I don't really like this solution either to be honest, but it's better than tampering with the DMA buffer).

**Comment by bugadani** [comment]
Sorry @bjoernQ I managed to completely hijack this PR, do you want me to send in the original fix separately?

**Comment by bjoernQ** [comment]
> Sorry @bjoernQ I managed to completely hijack this PR, do you want me to send in the original fix separately?

No problem - thanks for taking care of this

File: esp-hal/build.rs [hunk 1]
```diff
@@ -128,11 +128,18 @@ fn main() -> Result<(), Box<dyn Error>> {
...
-            "Places the SPI driver in RAM for better performance",
-        )],
+        &[
+            (
+                "place-spi-driver-in-ram",
+                Value::Bool(false),
+                "Places the SPI driver in RAM for better performance",
+            ),
+            (
+                "esp32-spi-address-workaround",
```
Comment (MabezDev) [inline esp-hal/build.rs:138]: This should probably mention half duplex somewhere, just to avoid confusion, even though it is implied when talking about addresses.

**Review by MabezDev — CHANGES_REQUESTED** [review]

**Review by MabezDev — APPROVED** [review]
LGTM, thanks!

File: esp-hal/src/spi/master.rs [hunk 2]
```diff
@@ -1374,6 +1425,41 @@ mod dma {
                 return Err((Error::MaxDmaTransferSizeExceeded, self, buffer));
             }
 
+            #[cfg(all(esp32, spi_address_workaround))]
+            {
+                // On the ESP32, if we don't have data, the address is always sent
+                // on a single line, regardless of its data mode.
+                if bytes_to_write == 0 && address.mode() != SpiDataMode::Single {
+                    let bytes_to_write = address.width().div_ceil(8);
+                    let addr_bytes = address.value().to_le_bytes();
```
Comment (bugadani) [inline esp-hal/src/spi/master.rs:1434]: Don't be hasty, I need to verify if I got the endianness right here.

Comment (Dominaezzz) [reply esp-hal/src/spi/master.rs:1434]: iirc the bit order of the data phase can changed so you'll probably have to read that register bit to decide the endianness here.

File: esp-hal/build.rs [hunk 3]
```diff
@@ -128,11 +128,18 @@ fn main() -> Result<(), Box<dyn Error>> {
...
-            "Places the SPI driver in RAM for better performance",
-        )],
+        &[
+            (
+                "place-spi-driver-in-ram",
+                Value::Bool(false),
+                "Places the SPI driver in RAM for better performance",
+            ),
+            (
+                "spi-address-workaround",
```
Comment (Dominaezzz) [inline esp-hal/build.rs:138]: Do you reckon libraries may want to set this?

File: esp-hal/src/spi/master.rs (hunk 2 above)
Comment (bugadani) [reply esp-hal/src/spi/master.rs:1434]: SPI_WR_BIT_ORDER affects all (CMD, ADDR and DATA) phases so I think I'm fine here.

Comment (bugadani) [reply esp-hal/src/spi/master.rs:1434]: That being said, I wanted to look at this with a logic analyzer because this workaround exists due to the hardware not doing what it's supposed to.

**Review by JurajSadel — APPROVED** [review]
Thanks!

File: esp-hal/build.rs (hunk 3 above)
Comment (MabezDev) [reply esp-hal/build.rs:138]: There should be one source of truth for the config, and it should lie in the hands of the user. In this case, we've enabled it by default, which is a sane thing to do, and users can opt-out. One thing libraries can do is detect if the setting is enabled and either warn/panic if it should be - but even this I would discourage unless the library functionality depended on it.

**Comment by bugadani** [comment]
Hold on there's still something not quite right here :)

File: esp-hal/src/spi/master.rs (hunk 2 above)
Comment (bugadani) [reply esp-hal/src/spi/master.rs]: Good thing I checked. The bit works as expected, but the address is encoded as big-endian so that had to be aligned.

Demo that we now generate the same waveform with or without data. 2 lines only, because my ESP32 devkit doesn't have enough pins 😅

image

Comment (Dominaezzz) [reply esp-hal/src/spi/master.rs]: Nice!

I just remembered, will this work as the user expects if they specify a dummy phase?

Comment (bugadani) [reply esp-hal/src/spi/master.rs]: No, the dummy phase gets moved to before the address which is wrong. But that'll need to be addressed later as there are a few different approaches to deal with that (error, ignore, emulate). This current PR is done the way it is.
