### PR TITLE
Fix known SPI issues

### LINKED ISSUE #2098: ESP32-S2: SPI DMA test_asymmetric_dma_transfer fails
For some reason, [S2 HIL](https://github.com/esp-rs/esp-hal/actions/runs/10717649673/job/29718015468) is failing this test, I can also reproduce it locally.  Not sure why it only happens in S2 and when using different buffer sizes (using `dma_buffers!(4,4)` passes the test)

`main` doesnt have any issue with this test in S2

_Originally posted by @SergioGasquez in https://github.com/esp-rs/esp-hal/pull/2074#discussion_r1745182546_

See https://github.com/esp-rs/esp-hal/pull/2074#discussion_r1746719403 for more information

### LINKED ISSUE #2186: ESP32: test_symmetric_dma_transfer test broken
Disabled in #2185, should be debugged and re-enabled.

Fun fact: test passes without `--release`.

### PR DESCRIPTION
**Pull request by bugadani**
## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [x] I have updated existing examples or added new ones (if applicable).
- [x] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [x] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [x] I have added necessary changes to user code to the [Migration Guide](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/MIGRATING-0.21.md).
- [x] My changes are in accordance to the [esp-rs API guidelines](https://github.com/esp-rs/esp-hal/blob/main/documentation/API-GUIDELINES.md)

#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/documentation/CONTRIBUTING.md) and followed its instructions.

#### Description

Changes include:
- Guarantee 4-byte alignment which is needed for some reason for PDMA
- Use `is_done` in `wait` to actually wait for the DMA to finish transferring from SPI to memory. This prevents weird test failures where an assert fails, then prints that the buffer and the expected value match.
- Clear interrupts after configuring DMA, which fixes the second call to `dma_transfer`
- Reintroduces a short wait for ESP32, which doesn't have an update bit so it starts transferring data before the DMA engine is ready.

Fixes #2098
Fixes #2186

#### Testing

yes

### CODE REVIEW

File: esp-hal/src/dma/mod.rs [hunk 1]
```diff
@@ -414,15 +434,15 @@ macro_rules! dma_circular_descriptors {
 #[macro_export]
 macro_rules! dma_buffers_chunk_size {
```
Comment (bugadani) [inline esp-hal/src/dma/mod.rs:435]: Fun sneaky breaking change: these now return a `&mut [u8]` instead of `&mut [u8; T/RX_SIZE]`, which is funny because it can't be directly passed to mem2mem start_transaction.

File: esp-hal/src/dma/mod.rs [hunk 2]
```diff
@@ -397,6 +399,24 @@ macro_rules! dma_circular_descriptors {
     };
 }
 
+/// Allocates a DMA buffer with a specific size, aligned to 4 bytes
+#[doc(hidden)]
+#[macro_export]
+macro_rules! allocate_dma_buffer {
```
Comment (liebman) [inline esp-hal/src/dma/mod.rs:405]: not sure I like this name as it implies it's using the allocator... maybe `declare_dma_buffer`?

Comment (bugadani) [reply esp-hal/src/dma/mod.rs]: Works for me

File: hil-test/tests/spi_full_duplex.rs [hunk 3]
```diff
@@ -152,4 +182,328 @@ mod tests {
...
+            .map_err(|e| e.0)
+            .unwrap();
+        let (spi, (dma_rx_buf, mut dma_tx_buf)) = transfer.wait();
+        assert_eq!(dma_tx_buf.as_slice()[0..2], dma_rx_buf.as_slice()[0..2]);
+
+        // Try transfer again to make sure DMA isn't in a broken state.
+
+        dma_tx_buf.fill(&[0xaa, 0xdd, 0xef, 0xbe]);
+
+        // TODO: The following transfer doesn't work correctly as the previous transfer
```
Comment (Dominaezzz) [inline hil-test/tests/spi_full_duplex.rs:307]: Oooh, this works fine now?

File: esp-hal/src/dma/mod.rs (hunk 1 above)
Comment (Dominaezzz) [reply esp-hal/src/dma/mod.rs:435]: > Unfortunately, PDMA writes out of bounds for transfers of length 2 and 3

Is this in the TRM or esp-idf?

Comment (bugadani) [reply esp-hal/src/dma/mod.rs:435]: IDF just downright ignores the problem and aligns the buffers by default to either 4 bytes or to some cache-dependent value that I ignored.

I didn't find anything in the 32/S2 TRMs, maybe I missed it.

However, I did find RX bytes in my TX buffer during testing :) Before the RX/TX swap we were simply lucky that the overflow was written to somewhere we didn't care about in the tests.

File: hil-test/tests/spi_full_duplex.rs (hunk 3 above)
Comment (bugadani) [reply hil-test/tests/spi_full_duplex.rs:307]: I think so

File: esp-hal/MIGRATING-0.20.md [hunk 4]
```diff
@@ -198,3 +198,32 @@ let mut i8080 = I8080::new(....);
 - i8080.send(0x12, 0, &[0, 1, 2, 3, 4]);
 + i8080.send(0x12u8, 0, &[0, 1, 2, 3, 4]);
 ```
+
+## Changes to DMA buffers
+
+The `dma_buffer_*` macros now return buffers as `&mut [u8]` instead of `&mut [u8; SIZE]`.
+This means that these buffer need to be passed by reference to the following functions:
+ - `I2sTx`: `start_tx_transfer`, `write_dma`, `write_dma_circular`, `write_dma_async`, `write_dma_circular_async`
```
Comment (bugadani) [inline esp-hal/MIGRATING-0.20.md:206]: Do we have some unfinished DMA buffer rework here? 🤣

File: esp-hal/src/dma/mod.rs (hunk 1 above)
Comment (Dominaezzz) [reply esp-hal/src/dma/mod.rs:435]: The ESP32 TRM says buffer and size of the descriptor must be word aligned for all peripherals.

The ESP32-S2 TRM seems to allow byte-addressable access. Did you observe the out of bounds access on the S2 as well?

Mind adding a comment somewhere that the word alignment is only required for the ESP32 (and possibly S2 if confirmed)?

File: esp-hal/src/dma/mod.rs [hunk 5]
```diff
@@ -397,6 +399,24 @@ macro_rules! dma_circular_descriptors {
     };
 }
 
+/// Allocates a DMA buffer with a specific size, aligned to 4 bytes
+#[doc(hidden)]
+#[macro_export]
+macro_rules! declare_aligned_dma_buffer {
+    ($name:ident, $size:expr) => {
+        static mut $name: [u32; ($size + 3) / 4] = [0; ($size + 3) / 4];
```
Comment (Dominaezzz) [inline esp-hal/src/dma/mod.rs:407]:
```suggestion
        static mut $name: [u32; $size.div_ceil(4)] = [0; $size.div_ceil(4)];
```

I think you can also do something like this to get alignment with less `unsafe`.
```Rust
#[repr(align(4))]
struct Data([u8; $size.div_ceil(4)]);
static mut $name: Data = ....;
name.0
```

File: esp-hal/src/dma/mod.rs [hunk 6]
```diff
@@ -397,6 +399,24 @@ macro_rules! dma_circular_descriptors {
...
+    };
+}
+
+/// Allocates a DMA buffer with a specific size, aligned to 4 bytes
+#[doc(hidden)]
+#[macro_export]
+macro_rules! as_bytes_mut {
+    ($name:ident, $size:expr) => {
+        unsafe { core::slice::from_raw_parts_mut($name.as_mut_ptr() as *mut u8, $size) }
```
Comment (Dominaezzz) [inline esp-hal/src/dma/mod.rs:416]: You could cast this to `[u8; $size]` to avoid the breaking change but idk how big a deal it is.

File: esp-hal/src/dma/mod.rs (hunk 5 above)
Comment (bugadani) [reply esp-hal/src/dma/mod.rs:407]: "Can't call `div_ceil` on an ambiguous numeric type" or something similar

Comment (bugadani) [reply esp-hal/src/dma/mod.rs:407]: Also would complain about redefining Data

File: esp-hal/src/dma/mod.rs (hunk 6 above)
Comment (bugadani) [reply esp-hal/src/dma/mod.rs]: Thanks, good call

File: esp-hal/src/dma/mod.rs (hunk 5 above)
Comment (Dominaezzz) [reply esp-hal/src/dma/mod.rs:407]: > Also would complain about redefining Data

True, might be worth making a type for it in the hal. And users could use it in other scenarios, like with `alloc`.

Bah, the numeric type thing is annoying.

**Comment by bugadani** [comment]
Ah finally CI reproduces my local issues with ESP32. Fun!

File: esp-hal/src/dma/mod.rs (hunk 5 above)
Comment (bugadani) [reply esp-hal/src/dma/mod.rs:407]: I could just cast to usize but it'd just end up being more code than manual rounding up.

Comment (liebman) [reply esp-hal/src/dma/mod.rs:407]: what about [aligned](https://crates.io/crates/aligned)?

Comment (bugadani) [reply esp-hal/src/dma/mod.rs:407]: I'll invoke my oneliner rule against aligned. We don't use that anywhere else except in examples, so I'll not introduce a new dependency to rework a oneliner.

File: esp-hal/CHANGELOG.md [hunk 7]
```diff
@@ -45,17 +45,17 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 - Changed the parameters of `Spi::with_pins` to no longer be optional (#2133)
 - Renamed `DummyPin` to `NoPin` and removed all internal logic from it. (#2133)
 - The `NO_PIN` constant has been removed. (#2133)
+- The various `dma_buffer` macros now return the buffers as `&mut [u8]` (#2179)
```
Comment (Dominaezzz) [inline esp-hal/CHANGELOG.md:48]: No longer the case

File: esp-hal/CHANGELOG.md [hunk 8]
```diff
@@ -45,17 +45,17 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
...
 
 - SHA driver can now be safely used in multiple contexts concurrently (#2049)
 - Fixed an issue with DMA transfers potentially not waking up the correct async task (#2065)
 - Fixed an issue with LCD_CAM i8080 where it would send double the clocks in 16bit mode (#2085)
 - Fix i2c embedded-hal transaction (#2028)
-- Fix SPI DMA alternating `write` and `read` for ESP32 and ESP32-S2 (#2131)
 - Fix I2C ending up in a state when only re-creating the peripheral makes it useable again (#2141)
-- Fix `SpiBus::transfer` transferring data twice in some cases (#2159)
 - Fixed UART freezing when using `RcFast` clock source on ESP32-C2/C3 (#2170)
+- Fixed various SPI issues (#2131, #2159, #2179)
```
Comment (Dominaezzz) [inline esp-hal/CHANGELOG.md:58]: If the change log entry is going to be vague then the PR title should be more descriptive I think.
Otherwise it's hard to know what's fixed and if you're affected or not.

File: esp-hal/src/dma/mod.rs (hunk 5 above)
Comment (Dominaezzz) [reply esp-hal/src/dma/mod.rs:407]: On second thought, I think it might be better to not "lie" to the user about the size here and assert (at compile time?) that `$size % 4 == 0` (only on the PDMA chips if possible), rather than discretely alter the size for the user.
Better for a user's program to not compile than to subtly/silently send/receive more bytes than intended.
Having said that, changing the size of the returned buffer (or asserting) is a breaking change.

File: esp-hal/src/spi/master.rs [hunk 9]
```diff
@@ -2346,101 +2335,83 @@ pub trait InstanceDma: Instance {
...
-                .clear_bit_by_one()
-                .dma_outfifo_empty_err()
-                .clear_bit_by_one()
-                .trans_done()
-                .clear_bit_by_one()
-                .mst_rx_afifo_wfull_err()
-                .clear_bit_by_one()
-                .mst_tx_afifo_rempty_err()
-                .clear_bit_by_one()
+            w.dma_infifo_full_err().clear_bit_by_one();
```
Comment (Dominaezzz) [inline esp-hal/src/spi/master.rs:2390]: Woah! Did you manage to convince bjoernQ that this style is better/clearer?

Comment (bugadani) [reply esp-hal/src/spi/master.rs:2390]: no, I'm strongarming this :D

File: esp-hal/CHANGELOG.md (hunk 8 above)
Comment (bugadani) [reply esp-hal/CHANGELOG.md:58]: I guess I can split the PR up and title it less vaguely but that looks unnecessary busywork. I guess I can restore the changelog entries but at the end it's actually hard to know how wide reaching these changes are, apart from "fixes failing tests".

File: esp-hal/src/spi/master.rs (hunk 9 above)
Comment (bugadani) [reply esp-hal/src/spi/master.rs:2390]: @bjoernQ did you have something against this style? I find pairing the value with the bitfield in the same line a lot easier to decode at a quick glance.

File: esp-hal/CHANGELOG.md (hunk 7 above)
Comment (MabezDev) [inline esp-hal/CHANGELOG.md:48]: Is this changelog still correct? It looks to me like we're returning `&mut [u8; SIZE]`?

Comment (bugadani) [reply esp-hal/CHANGELOG.md:48]: yup Dominic also noticed, I rebased away the commit that removed it

Comment (MabezDev) [reply esp-hal/CHANGELOG.md:48]: Dominic beat me to it :D

File: esp-hal/src/dma/mod.rs (hunk 5 above)
Comment (bugadani) [reply esp-hal/src/dma/mod.rs:411]: Technically, we shouldn't end up sending/receiving more data, all we are doing here is making sure nothing gets placed into the 2 bytes that may be written out of bounds. What the user and the HAL ends up seeing is the same sized buffer they asked for.

I agree that this is a terrible hack to solve the problem, I just don't know any better solutions. Fun fact: the DMA works as expected for 1 mod 4 buffers, which makes me think this might be a hardware issue. But I admit I stopped reading the TRM after only 2 hours or so, hunting for a clue, so I may have missed the "auto-burst mode if you transfer more than 1 byte" bit in one of the registers.

**Review by MabezDev — APPROVED** [review]
LGTM, thanks!

File: esp-hal/src/spi/master.rs (hunk 9 above)
Comment (bjoernQ) [reply esp-hal/src/spi/master.rs:2390]: I was never really advocating for any style but I agree this is more readable - I also think we had an issue regarding the style somewhere. 

Ok - can't find it for some reason

I was never really advocating for any style but I agree this is more readable - I also think we had an issue regarding the style somewhere. I think the original style "just happened"

Ideally, we should just not mix different styles in the same file (but well - blowing up a five-line PR by changing style in thousands of lines is also problematic)

File: hil-test/tests/spi_full_duplex.rs [hunk 10]
```diff
@@ -1,7 +1,7 @@
 //! SPI Full Duplex test suite.
 
 //% CHIPS: esp32 esp32c2 esp32c3 esp32c6 esp32h2 esp32s2 esp32s3
-//% FEATURES: generic-queue
+//% FEATURES: generic-queue defmt
```
Comment (bjoernQ) [inline hil-test/tests/spi_full_duplex.rs:4]: I don't think we want to keep `defmt`

File: esp-hal/src/spi/master.rs (hunk 9 above)
Comment (bugadani) [reply esp-hal/src/spi/master.rs:2390]: I plan on cleaning this up as I go. I remember @jessebraham removing the `#[rustfmt::skip]` that then reformatted everything into this linear thing. Jesse, do you have a preference either way?

File: hil-test/tests/spi_full_duplex.rs (hunk 10 above)
Comment (bugadani) [reply hil-test/tests/spi_full_duplex.rs:4]: dammit I always forget to remove these

Comment (Dominaezzz) [reply hil-test/tests/spi_full_duplex.rs]: Protip, add it as a default feature in cargo.toml (and don't commit it).

Comment (bugadani) [reply hil-test/tests/spi_full_duplex.rs]: As you can see, my issue is with the "don't commit it" part :)

Comment (bjoernQ) [reply hil-test/tests/spi_full_duplex.rs]: I was thinking about a pre-commit-hook which checks for a keyword like STOPSHIP or something - committing stuff I don't want to commit happens too often for me, too

File: esp-hal/src/spi/master.rs (hunk 9 above)
Comment (jessebraham) [reply esp-hal/src/spi/master.rs:2390]: Doesn't matter to me

**Comment by bugadani** [comment]
I solemnly wov that the ESP32 tests pass locally.

**Review by jessebraham — APPROVED** [review]
@bugadani Sounds good 😁 Changes LGTM, thanks!
