### PR TITLE
H2: Fix ECO2+ RcFast clock calibration

### LINKED ISSUE #5321: Broken clocks on `esp32h2 rev 0.2`
## Bug description

Rev `0.0` and `0.1` work fine.

## To Reproduce
`cargo xtask run example sleep_timer --package qa-test --chip esp32h2`

```rust
up and runnning!
reset reason: ChipPowerOn
wake reason: Undefined
sleeping!


====================== PANIC ======================
panicked at /Users/jurajsadel/esp-rs/esp-hal-main/esp-hal/src/rtc_cntl/sleep/esp32h2.rs:545:9:
attempt to divide by zero
```
## Expected behavior

It works

## Environment

- Target device: [e.g. ESP32-H2]
```rust
espflash board-info
[2026-04-08T14:52:56Z INFO ] Serial port: '/dev/cu.usbserial-1140'
[2026-04-08T14:52:56Z INFO ] Connecting...
[2026-04-08T14:52:57Z INFO ] Using flash stub
[2026-04-08T14:52:57Z WARN ] Setting baud rate higher than 115,200 can cause issues
Chip type:         esp32h2 (revision v0.2)
Crystal frequency: 32 MHz
Flash size:        4MB
Features:          BLE
MAC address:       60:55:f9:f7:39:92

Security Information:
=====================
Flags: 0x00000000 (0)
Key Purposes: [0, 0, 0, 0, 0, 0, 12]
Chip ID: 16
API Version: 0
Secure Boot: Disabled
Flash Encryption: Disabled
SPI Boot Crypt Count (SPI_BOOT_CRYPT_CNT): 0x0
```

- Crate name and version: [e.g. esp-hal 1.0.0]

### PR DESCRIPTION
**Pull request by JurajSadel**
This PR addresses necessary calibration steps for ECO2+ H2.

closes https://github.com/esp-rs/esp-hal/issues/5321

### CODE REVIEW

File: esp-hal/src/clock/mod.rs [hunk 1]
```diff
@@ -67,6 +67,12 @@ pub mod ll {
 
 #[cfg(timergroup_rc_fast_calibration_divider)]
 use crate::efuse::ChipRevision;
+#[cfg(all(
+    soc_has_clock_node_timg_calibration_clock,
+    timergroup_rc_fast_calibration_divider,
+    esp32h2
```
Comment (bugadani) [inline esp-hal/src/clock/mod.rs]:
```suggestion
    esp32h2
```

No need to overcomplicate this, if you target a single device - although I'd add metadata to gate based on the presence of `tick_enable`, we might need this for later chips.

File: esp-hal/src/clock/mod.rs [hunk 2]
```diff
@@ -352,6 +366,17 @@ impl Clocks {
         clocks::configure_timg_calibration_clock(clocks, rtc_clock);
         clocks::request_timg_calibration_clock(clocks);
 
+        // Align with IDF ECO2+ RC_FAST calibration flow.
+        #[cfg(all(
+            timergroup_rc_fast_calibration_divider,
+            timergroup_rc_fast_calibration_tick_enable
+        ))]
```
Comment (bugadani) [inline esp-hal/src/clock/mod.rs]: The register description is: "Configures the clock divisor for RC_FAST_CLK". To me this means that `timergroup_rc_fast_calibration_tick_enable` implies `timergroup_rc_fast_calibration_divider`. Why do we need both in the cfg condition?

Comment (JurajSadel) [reply esp-hal/src/clock/mod.rs]: You are right, I cleaned cfg gates, thanks!

**Review by bugadani — APPROVED** [review]
