### PR TITLE
Make sure .flash_desc and .rodata are merged by the tooling

### LINKED ISSUE #4842: ESP32-C6 asserts on boot when using serde_json
## Bug description

While beginning work on a weather project (grabbing forecast from an API, displaying it) my ESP32-C6 started hitting an assert on boot before ever hitting my code. As far as I can tell, any usage of serde_json causes it to fail to boot.

## To Reproduce

1. Clone https://github.com/AlyoshaVasilieva/esp-repro, compile and flash onto an ESP32-C6 in release mode.
2. It should assert on boot.
3. Comment out the lines https://github.com/AlyoshaVasilieva/esp-repro/blob/55b8429ae38abeb6d4579e7792e41beb3832adc4/src/bin/main.rs#L122-L123, uncomment the lines https://github.com/AlyoshaVasilieva/esp-repro/blob/55b8429ae38abeb6d4579e7792e41beb3832adc4/src/bin/main.rs#L117-L118
4. It works. Only changes are now it's just reading text, no deserialization via serde json (so I assume serde gets LTO'd out of the build entirely).

Log from running the broken build:

```
ESP-ROM:esp32c6-20220919
Build:Sep 19 2022
rst:0x15 (USB_UART_HPSYS),boot:0x1c (SPI_FAST_FLASH_BOOT)
Saved PC:0x40800822
SPIWP:0xee
mode:DIO, clock div:2
load:0x40875730,len:0x175c
load:0x4086b910,len:0xec8
load:0x4086e610,len:0x31c4
entry 0x4086b91a
I (23) boot: ESP-IDF v5.5.1-838-gd66ebb86d2e 2nd stage bootloader
I (24) boot: compile time Nov 27 2025 09:46:10
I (25) boot: chip revision: v0.1
I (25) boot: efuse block revision: v0.3
I (28) boot.esp32c6: SPI Speed      : 80MHz
I (32) boot.esp32c6: SPI Mode       : DIO
I (36) boot.esp32c6: SPI Flash Size : 4MB
I (39) boot: Enabling RNG early entropy source...
I (44) boot: Partition Table:
I (46) boot: ## Label            Usage          Type ST Offset   Length
I (53) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (59) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (66) boot:  2 factory          factory app      00 00 00010000 003f0000
I (72) boot: End of partition table
I (76) esp_image: segment 0: paddr=00010020 vaddr=42000020 size=00100h (   256) map
I (83) esp_image: segment 1: paddr=00010128 vaddr=40800000 size=00010h (    16) load
I (90) esp_image: segment 2: paddr=00010140 vaddr=42000140 size=1c854h (116820) map
I (120) esp_image: segment 3: paddr=0002c99c vaddr=40800010 size=00014h (    20) load
I (121) esp_image: segment 4: paddr=0002c9b8 vaddr=4201c9b8 size=d3064h (864356) map
I (289) esp_image: segment 5: paddr=000ffa24 vaddr=40800024 size=10ef0h ( 69360) load
I (305) esp_image: segment 6: paddr=0011091c vaddr=40810f18 size=001e0h (   480) load
I (310) boot: Loaded app from partition at offset 0x10000
I (310) boot: Disabling RNG early entropy source...
Assert failed in unpack_load_app, bootloader_utility.c:836 (rom_index < 2)
```

Log from the working build:

```
ESP-ROM:esp32c6-20220919
Build:Sep 19 2022
rst:0x15 (USB_UART_HPSYS),boot:0x1c (SPI_FAST_FLASH_BOOT)
Saved PC:0x40800826
SPIWP:0xee
mode:DIO, clock div:2
load:0x40875730,len:0x175c
load:0x4086b910,len:0xec8
load:0x4086e610,len:0x31c4
entry 0x4086b91a
I (23) boot: ESP-IDF v5.5.1-838-gd66ebb86d2e 2nd stage bootloader
I (24) boot: compile time Nov 27 2025 09:46:10
I (25) boot: chip revision: v0.1
I (25) boot: efuse block revision: v0.3
I (28) boot.esp32c6: SPI Speed      : 80MHz
I (32) boot.esp32c6: SPI Mode       : DIO
I (36) boot.esp32c6: SPI Flash Size : 4MB
I (39) boot: Enabling RNG early entropy source...
I (44) boot: Partition Table:
I (46) boot: ## Label            Usage          Type ST Offset   Length
I (53) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (59) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (66) boot:  2 factory          factory app      00 00 00010000 003f0000
I (72) boot: End of partition table
I (76) esp_image: segment 0: paddr=00010020 vaddr=42000020 size=182cch ( 99020) map
I (102) esp_image: segment 1: paddr=000282f4 vaddr=40800000 size=00014h (    20) load
I (103) esp_image: segment 2: paddr=00028310 vaddr=42018310 size=cd2b4h (840372) map
I (266) esp_image: segment 3: paddr=000f55cc vaddr=40800014 size=10eb8h ( 69304) load
I (282) esp_image: segment 4: paddr=0010648c vaddr=40810ed0 size=001e0h (   480) load
I (287) boot: Loaded app from partition at offset 0x10000
I (287) boot: Disabling RNG early entropy source...
[WARN ] esp_wifi_internal_tx(interface, ptr, len) returned an error: 12290 (12290) (esp_radio src/wifi/mod.rs:1438)
start connection task
Starting wifi
Wifi started!
Scan
AccessPointInfo { ssid: "REDACTED", bssid: [REDACTED], channel: 1, secondary_channel: None, signal_strength: -45, auth_method: Some(Wpa2Personal), country: Some(CountryInfo { country: [85, 83], operating_class: AllEnvironments }) }
About to connect...
Wifi connected!
Waiting to get IP address...
Got IP: 192.168.1.101/24
connecting...
connected!
{
  "userId": 1,
  "id": 1,
  "title": "delectus aut autem",
  "completed": false
}
```

`cargo readobj --release -- --section-headers --section-details` for the working build:

```
There are 38 section headers, starting at offset 0x11c9ab8:

Section Headers:
  [Nr] Name
       Type            Addr     Off    Size   ES   Lk Inf Al
       Flags
  [ 0]
       NULL            00000000 000000 000000 00   0   0  0
       [00000000]:
  [ 1] .defmt
       PROGBITS        00000000 0f9610 0000ee 00   0   0  1
       [00200000]: OS (00200000)
  [ 2] .trap
       PROGBITS        40800000 001000 000654 00   0   0  256
       [00000006]: ALLOC, EXEC
  [ 3] .rwtext
       PROGBITS        40800654 001654 0011c0 00   0   0  4
       [00000006]: ALLOC, EXEC
  [ 4] .rwtext.wifi
       PROGBITS        40801814 002814 00d5c4 00   0   0  2
       [00000006]: ALLOC, EXEC
  [ 5] .data
       PROGBITS        4080edd8 00fdd8 0020f4 00   0   0  8
       [00000013]: WRITE, ALLOC, MERGE
  [ 6] .data.wifi
       PROGBITS        40810ed0 011ed0 0001e0 00   0   0  8
       [00000003]: WRITE, ALLOC
  [ 7] .bss
       NOBITS          408110b0 0120b0 013d98 00   0   0  8
       [00000003]: WRITE, ALLOC
  [ 8] .noinit
       NOBITS          40824e48 0120b0 000000 00   0   0  4
       [00000003]: WRITE, ALLOC
  [ 9] .flash.appdesc
       PROGBITS        42000020 013020 000100 00   0   0  4
       [00200002]: ALLOC, OS (00200000)
  [10] .rodata
       PROGBITS        42000120 013120 00dfc0 00   0   0  8
       [00000032]: ALLOC, MERGE, STRINGS
  [11] .rodata.wifi
       PROGBITS        4200e0e0 0210e0 00a20c 00   0   0  4
       [00000002]: ALLOC
  [12] .text_gap
       NOBITS          420182ec 02b2ec 000024 00   0   0  1
       [00000002]: ALLOC
  [13] .text
       PROGBITS        42018310 02b310 0cd2b2 00   0   0  4
       [00000006]: ALLOC, EXEC
  [14] .rtc_fast.text
       PROGBITS        50000000 0f85c2 000000 00   0   0  1
       [00000002]: ALLOC
  [15] .rtc_fast.data
       PROGBITS        50000000 0f85c2 000000 00   0   0  1
       [00000002]: ALLOC
  [16] .rtc_fast.bss
       NOBITS          50000000 0f85c2 000000 00   0   0  1
       [00000002]: ALLOC
  [17] .rtc_fast.persistent
       NOBITS          50000000 0f85c2 000000 00   0   0  1
       [00000002]: ALLOC
  [18] .stack
       NOBITS          40824e48 0f8e48 0497c8 00   0   0  4
       [00000002]: ALLOC
  [19] .dram2_uninit
       NOBITS          4086e610 0f9610 010000 00   0   0  4
       [00000003]: WRITE, ALLOC
  [20] .espressif.metadata
       PROGBITS        00000000 0f96fe 00001c 00   0   0  1
       [00200000]: OS (00200000)
  [21] .eh_frame
       PROGBITS        00000000 0f971c 00a9a4 00   0   0  4
       [00000000]:
  [22] .debug_loc
       PROGBITS        00000000 1040c0 355e94 00   0   0  1
       [00000000]:
  [23] .debug_abbrev
       PROGBITS        00000000 459f54 017934 00   0   0  1
       [00000000]:
  [24] .debug_info
       PROGBITS        00000000 471888 3ac0b2 00   0   0  1
       [00000000]:
  [25] .debug_aranges
       PROGBITS        00000000 81d93a 009658 00   0   0  1
       [00000000]:
  [26] .debug_ranges
       PROGBITS        00000000 826f92 2133c0 00   0   0  1
       [00000000]:
  [27] .debug_str
       PROGBITS        00000000 a3a352 2ad4cc 01   0   0  1
       [00000030]: MERGE, STRINGS
  [28] .comment
       PROGBITS        00000000 ce781e 00012e 01   0   0  1
       [00000030]: MERGE, STRINGS
  [29] .riscv.attributes
       RISCV_ATTRIBUTES 00000000 ce794c 000063 00  0   0  1
       [00000000]:
  [30] .debug_line
       PROGBITS        00000000 ce79af 0fe232 00   0   0  1
       [00000000]:
  [31] .debug_loclists
       PROGBITS        00000000 de5be1 0000e4 00   0   0  1
       [00000000]:
  [32] .debug_rnglists
       PROGBITS        00000000 de5cc5 00003a 00   0   0  1
       [00000000]:
  [33] .debug_line_str
       PROGBITS        00000000 de5cff 00010f 01   0   0  1
       [00000030]: MERGE, STRINGS
  [34] .debug_frame
       PROGBITS        00000000 de5e10 00a3a0 00   0   0  4
       [00000000]:
  [35] .symtab
       SYMTAB          00000000 df01b0 2b8140 10   37  174574 4
       [00000000]:
  [36] .shstrtab
       STRTAB          00000000 10a82f0 0001b4 00  0   0  1
       [00000000]:
  [37] .strtab
       STRTAB          00000000 10a84a4 121611 00  0   0  1
       [00000000]:
```

`cargo readobj --release -- --section-headers --section-details` for the broken build:

```
There are 38 section headers, starting at offset 0x12339dc:

Section Headers:
  [Nr] Name
       Type            Addr     Off    Size   ES   Lk Inf Al
       Flags
  [ 0]
       NULL            00000000 000000 000000 00   0   0  0
       [00000000]:
  [ 1] .defmt
       PROGBITS        00000000 103610 0000ee 00   0   0  1
       [00200000]: OS (00200000)
  [ 2] .trap
       PROGBITS        40800000 001000 000654 00   0   0  256
       [00000006]: ALLOC, EXEC
  [ 3] .rwtext
       PROGBITS        40800654 001654 0011c0 00   0   0  4
       [00000006]: ALLOC, EXEC
  [ 4] .rwtext.wifi
       PROGBITS        40801814 002814 00d5c4 00   0   0  2
       [00000006]: ALLOC, EXEC
  [ 5] .data
       PROGBITS        4080edd8 00fdd8 00213c 00   0   0  8
       [00000013]: WRITE, ALLOC, MERGE
  [ 6] .data.wifi
       PROGBITS        40810f18 011f18 0001e0 00   0   0  8
       [00000003]: WRITE, ALLOC
  [ 7] .bss
       NOBITS          408110f8 0120f8 013d98 00   0   0  8
       [00000003]: WRITE, ALLOC
  [ 8] .noinit
       NOBITS          40824e90 0120f8 000000 00   0   0  4
       [00000003]: WRITE, ALLOC
  [ 9] .flash.appdesc
       PROGBITS        42000020 013020 000100 00   0   0  4
       [00200002]: ALLOC, OS (00200000)
  [10] .rodata
       PROGBITS        42000140 013140 012648 00   0   0  64
       [00000032]: ALLOC, MERGE, STRINGS
  [11] .rodata.wifi
       PROGBITS        42012788 025788 00a20c 00   0   0  4
       [00000002]: ALLOC
  [12] .text_gap
       NOBITS          4201c994 02f994 000024 00   0   0  1
       [00000002]: ALLOC
  [13] .text
       PROGBITS        4201c9b8 02f9b8 0d3062 00   0   0  4
       [00000006]: ALLOC, EXEC
  [14] .rtc_fast.text
       PROGBITS        50000000 102a1a 000000 00   0   0  1
       [00000002]: ALLOC
  [15] .rtc_fast.data
       PROGBITS        50000000 102a1a 000000 00   0   0  1
       [00000002]: ALLOC
  [16] .rtc_fast.bss
       NOBITS          50000000 102a1a 000000 00   0   0  1
       [00000002]: ALLOC
  [17] .rtc_fast.persistent
       NOBITS          50000000 102a1a 000000 00   0   0  1
       [00000002]: ALLOC
  [18] .stack
       NOBITS          40824e90 102e90 049780 00   0   0  4
       [00000002]: ALLOC
  [19] .dram2_uninit
       NOBITS          4086e610 103610 010000 00   0   0  4
       [00000003]: WRITE, ALLOC
  [20] .espressif.metadata
       PROGBITS        00000000 1036fe 00001c 00   0   0  1
       [00200000]: OS (00200000)
  [21] .eh_frame
       PROGBITS        00000000 10371c 00b830 00   0   0  4
       [00000000]:
  [22] .debug_loc
       PROGBITS        00000000 10ef4c 363875 00   0   0  1
       [00000000]:
  [23] .debug_abbrev
       PROGBITS        00000000 4727c1 017a41 00   0   0  1
       [00000000]:
  [24] .debug_info
       PROGBITS        00000000 48a202 3c2fe8 00   0   0  1
       [00000000]:
  [25] .debug_aranges
       PROGBITS        00000000 84d1ea 009950 00   0   0  1
       [00000000]:
  [26] .debug_ranges
       PROGBITS        00000000 856b3a 217808 00   0   0  1
       [00000000]:
  [27] .debug_str
       PROGBITS        00000000 a6e342 2bcff0 01   0   0  1
       [00000030]: MERGE, STRINGS
  [28] .comment
       PROGBITS        00000000 d2b332 00012e 01   0   0  1
       [00000030]: MERGE, STRINGS
  [29] .riscv.attributes
       RISCV_ATTRIBUTES 00000000 d2b460 000063 00  0   0  1
       [00000000]:
  [30] .debug_line
       PROGBITS        00000000 d2b4c3 1053d8 00   0   0  1
       [00000000]:
  [31] .debug_loclists
       PROGBITS        00000000 e3089b 0000e4 00   0   0  1
       [00000000]:
  [32] .debug_rnglists
       PROGBITS        00000000 e3097f 00003a 00   0   0  1
       [00000000]:
  [33] .debug_line_str
       PROGBITS        00000000 e309b9 00010f 01   0   0  1
       [00000030]: MERGE, STRINGS
  [34] .debug_frame
       PROGBITS        00000000 e30ac8 00a3a0 00   0   0  4
       [00000000]:
  [35] .symtab
       SYMTAB          00000000 e3ae68 2ce0e0 10   37  180201 4
       [00000000]:
  [36] .shstrtab
       STRTAB          00000000 1108f48 0001b4 00  0   0  1
       [00000000]:
  [37] .strtab
       STRTAB          00000000 11090fc 12a8e0 00  0   0  1
       [00000000]:
```

`.rodata` alignment is 64 in the broken build, 8 in the working build.

Note: I tried to minimize it a bit but I ran into this when doing my first embedded hobby project in years so I'm rusty.

## Expected behavior

It boots.

## Environment

- Target device: ESP32-C6 revision 0.1 (WeAct ESP32-C6-MiNi)
```
Chip type:         esp32c6 (revision v0.1)
Crystal frequency: 40 MHz
Flash size:        4MB
Features:          WiFi 6, BT 5
MAC address:       54:32:04:32:c0:10

Security Information:
=====================
Flags: 0x00000000 (0)
Key Purposes: [0, 0, 0, 0, 0, 0, 12]
Chip ID: 13
API Version: 0
Secure Boot: Disabled
Flash Encryption: Disabled
SPI Boot Crypt Count (SPI_BOOT_CRYPT_CNT): 0x0
```
- Crate name and version: esp-hal 0b9e4e052ec181659b5feac7da3ade60643291b7 (also occurred on 1.0.0, which is what I started off with)

### PR DESCRIPTION
**Pull request by bjoernQ**
Fixes #4842

If some input section with an alignment >4 is going into `.ro_data`  we might produce a gap between `.flash_desc` and `.rodata` which makes tooling (at least espflash) emit more than two segments which go into flash.

The bootloader wants exactly two segments however.

---

Why not just use `SUBALIGN` to force input-sections to be aligned by 4?

That might be dangerous since code / hardware might require a specific alignment.

---

Why not add the "gap" to `.flash_desc`?

Tooling checks the size of this segment.

### CODE REVIEW

**Comment by bugadani** [comment]
I would like to see a HIL test for this

File: hil-test/src/bin/misc_non_drivers/simple.rs [hunk 1]
```diff
@@ -175,6 +175,29 @@ mod tests {
...
+    #[test]
+    fn can_boot() {
+        #[allow(unused)]
+        #[repr(align(64))]
+        struct Aligned {
+            data: [u8; 128],
+        }
+
+        #[used]
+        static ALIGNED: Aligned = Aligned { data: [0; 128] };
```
Comment (MabezDev) [inline hil-test/src/bin/misc_non_drivers/simple.rs]: This being static probably puts it in .rwdata or more likely bss, we should const this and/or use the specific linker section to ensure this test is testing the right thing.

Comment (bjoernQ) [reply hil-test/src/bin/misc_non_drivers/simple.rs]: it goes into .rodata

```
misc_non_drivers[ab9478271f7a08ef]::simple::tests::can_boot::ALIGNED      42002100 00000080 Definition Local
```

If it was `static mut` it would go into `.rwdata`/`.bss`

File: hil-test/src/bin/misc_non_drivers/simple.rs [hunk 2]
```diff
@@ -175,6 +175,29 @@ mod tests {
...
+    ///
+    /// The gap produced previously made tooling create three image segments but
+    /// the bootloader will refuse to boot anything with >2 segments in flash.
+    ///
+    /// Unfortunately the way things fail if this fails is "unfortunate"
+    /// (i.e. every test here fails with an unhelpful `ERROR probe_rs_debug::debug_info:Other("Stack
+    /// pointer is too far away to unwind")``)
+    #[test]
+    fn can_boot() {
+        #[allow(unused)]
```
Comment (bugadani) [inline hil-test/src/bin/misc_non_drivers/simple.rs]: This is used, right, so this attribute is not necessary?

Comment (bjoernQ) [reply hil-test/src/bin/misc_non_drivers/simple.rs]: well I would agree but the compiler didn't 🤷‍♂️ I can double check however

Comment (bjoernQ) [reply hil-test/src/bin/misc_non_drivers/simple.rs]: ah 🤦‍♂️
