### PR TITLE
Test and fix async RSA

### LINKED ISSUE #822: `esp32` - issue with `RSA` peripheral
Encountered a problem during implementing https://github.com/esp-rs/esp-hal/pull/790 :
Program run hangs in [this or similar blocks](https://github.com/esp-rs/esp-hal/blob/main/esp-hal-common/src/rsa/mod.rs#L179-L181C10) -> seems to be stuck in non-idle mode.

One idea where the problem is:
Every other chip (except of `esp32`) has a separate register for handling `IDLE` state (`RSA_IDLE_REG` for esp32sX or RSA_QUERY_IDLE for `esp32cX`), but on [esp32 it's checked through the `interrupt` register](https://github.com/esp-rs/esp-hal/blob/main/esp-hal-common/src/rsa/esp32.rs#L48-L50) on which async functionality depends -> conflict

### PR DESCRIPTION
**Pull request by bugadani**
Closes #822 I think?
cc #361

### CODE REVIEW

File: esp-hal/src/rsa/esp32sX.rs [hunk 1]
```diff
@@ -120,7 +120,7 @@ impl<'d, DM: crate::Mode> Rsa<'d, DM> {
     }
 
     /// Clears the RSA interrupt flag.
-    pub(super) fn clear_interrupt(&mut self) {
+    pub(super) fn clear_interrupt(&self) {
```
Comment (Dominaezzz) [inline esp-hal/src/rsa/esp32sX.rs:123]: Out of curiosity why'd you remove the `mut` here?

File: esp-hal/src/rsa/mod.rs [hunk 2]
```diff
@@ -373,49 +372,61 @@ pub(crate) mod asynch {
...
+        #[cfg_attr(esp32, allow(dead_code))]
+        instance: &'a Rsa<'d, Async>,
     }
 
-    impl<'d> RsaFuture<'d> {
-        /// Asynchronously initializes the RSA peripheral.
-        fn new(instance: &'d crate::peripherals::RSA) -> Self {
+    impl<'a, 'd> RsaFuture<'a, 'd> {
+        fn new(instance: &'a Rsa<'d, Async>) -> Self {
+            SIGNALED.store(false, Ordering::Relaxed);
```
Comment (Dominaezzz) [inline esp-hal/src/rsa/mod.rs:401]: Why not use `INT_RAW` here instead of a separate flag?

File: esp-hal/src/rsa/mod.rs [hunk 3]
```diff
@@ -373,49 +372,61 @@ pub(crate) mod asynch {
...
                 }
             }
 
             Self { instance }
         }
 
-        fn event_bit_is_clear(&self) -> bool {
-            // Looks weird, but we signal completion by disabling the interrupt.
+        fn is_done(&self) -> bool {
+            SIGNALED.load(Ordering::Relaxed)
```
Comment (Dominaezzz) [inline esp-hal/src/rsa/mod.rs:416]: This should definitely be `Acquire`

File: esp-hal/src/rsa/mod.rs (hunk 2 above)
Comment (Dominaezzz) [inline esp-hal/src/rsa/mod.rs:401]: This should definitely be `Ordering::Release`

**Review by Dominaezzz — COMMENTED** [review]
I'm mostly suggesting to follow #1835

File: esp-hal/src/rsa/mod.rs (hunk 2 above)
Comment (bugadani) [reply esp-hal/src/rsa/mod.rs:401]: What's that?

File: esp-hal/src/rsa/esp32sX.rs (hunk 1 above)
Comment (bugadani) [reply esp-hal/src/rsa/esp32sX.rs:123]: Because I was wrestling with this problem at midnight after 13 hours of work. There is probably an unreasonable amount of left-over from a bunch of back-and-forth changes. But the original reason was that the future holds on to `&Rsa` while at the same time we're doing operations on the same `&Rsa` so I needed this to be `&self` at one point. Probably not anymore, though.

File: esp-hal/src/rsa/mod.rs (hunk 2 above)
Comment (Dominaezzz) [reply esp-hal/src/rsa/mod.rs:401]: So every interrupt has 4 registers. INT_ENA, INT_ST, INT_CLR and INT_RAW.

`INT_ST = INT_RAW & INT_ENA`

Comment (bugadani) [reply esp-hal/src/rsa/mod.rs:401]: I'm not sure what you're referring to, the CPU interrupt, or the peripheral. The peripherals definitely don't have any of these.

File: esp-hal/src/rsa/mod.rs (hunk 3 above)
Comment (bugadani) [reply esp-hal/src/rsa/mod.rs:416]: I don't claim to understand memory orderings, but my understanding is that `Relaxed` should be safe here, it's also used in Mara's [book](https://marabos.nl/atomics/atomics.html#example-stop-flag) in an example of similar semantics.

I'd be happy to learn *why* this definitely has to be something else, if you would please take the time to explain or point me in the right direction.

File: esp-hal/src/rsa/mod.rs (hunk 2 above)
Comment (Dominaezzz) [reply esp-hal/src/rsa/mod.rs:401]: Oh apologies 😬, I just realized this peripheral doesn't have the usual interrupt bit setup as most of the other peripherals. Ignore this comment

Comment (bugadani) [reply esp-hal/src/rsa/mod.rs:401]: Yeah this is a huge pain point with these, there are 3 iterations of the peripheral, all of them annoying 🫠

Comment (Dominaezzz) [reply esp-hal/src/rsa/mod.rs:401]: Ideally there would normally be a way to check if the interrupt is set. Perhaps checking for idle?

Comment (bugadani) [reply esp-hal/src/rsa/mod.rs:401]: I can try some things, but not with today's brain. Yesterdays I've seen cases where, on the S3, the interrupt seemed to just disable itself for no good reason, without firing. So... I'm somewhat hesitant to touch this code right now.

File: esp-hal/src/rsa/mod.rs (hunk 3 above)
Comment (Dominaezzz) [reply esp-hal/src/rsa/mod.rs:416]: The best reference I have is https://doc.rust-lang.org/std/sync/atomic/enum.Ordering.html#variant.Acquire and possibly some Jon Gjengset videos on YouTube.

The reason to use `Acquire` here is users of `is_done` are relying on the invariant that if it returns true, all the stuff that they expect to be done has been done. Without `Acquire`, it's possible that it returns true before stuff is done.

Of course this needs to be paired with a `Release` in the interrupt handler to make sure everything is done before the boolean is marked true.

Lemme know if you want more words.

Comment (bugadani) [reply esp-hal/src/rsa/mod.rs:416]: > Without Acquire, it's possible that it returns true before stuff is done.

As the counterpart is in an interrupt handler, I think we can be confident everything will be done by the time this line executes and returns true 🤔

Comment (Dominaezzz) [reply esp-hal/src/rsa/mod.rs:416]: Yes that's one half of the equation. (We're assuming single core interrupts of course)

```Rust
while !fut.is_done() {}

// do other stuff.
// Without Acquire, the compiler (and CPU in theory, I don't think ESP32s do reordering) could move this to before the while loop.
```

**Comment by bugadani** [comment]
There are improvements to consider (like avoiding the AtomicBool on S3, if possible), but the current state is a definite improvement on what we have currently, so I'm marking this as a tentative Ready.

**Review by MabezDev — APPROVED** [review]
LGTM, thanks!

**Review by bjoernQ — APPROVED** [review]
LGTM
