### PR TITLE
Systimer improvements

### LINKED ISSUE #2431: esp-hal-embassy clock initialization with SysTimer Alarm panics shortly after
## Bug description

With esp-hal `v0.21.1`, initializing embassy with the SysTimer alarms results in a runtime panic, shortly after `esp_hal_embassy::init(...);`

## To Reproduce

1. With the following program:

```
#[main]
async fn main(spawner: Spawner) -> ! {
    esp_println::logger::init_logger_from_env();
    let peripherals = esp_hal::init(esp_hal::Config::default());

    let systimer = SystemTimer::new(peripherals.SYSTIMER).split::<Target>();
    let alarm0: AnyTimer = systimer.alarm0.into();
    let alarm1: AnyTimer = systimer.alarm1.into();
    esp_hal_embassy::init([alarm0, alarm1]);

    let mut cpu_control = CpuControl::new(peripherals.CPU_CTRL);
    let io = Io::new(peripherals.GPIO, peripherals.IO_MUX);

    // WiFi PHY start
    let timg0 = TimerGroup::new(peripherals.TIMG0);
    let mut rng = Rng::new(peripherals.RNG);
    esp_alloc::heap_allocator!(74 * 1024);
    let seed = ((rng.random() as u64) << 32) | (rng.random() as u64);
    let init = esp_wifi::init(
        esp_wifi::EspWifiInitFor::Wifi,
        timg0.timer0,
        rng,
        peripherals.RADIO_CLK,
    )
    .unwrap();
    let (wifi_interface, controller) =
        esp_wifi::wifi::new_with_mode(&init, peripherals.WIFI, WifiStaDevice).unwrap();
    ...
}
```

2. and the following dependencies in `Cargo.toml`:

```
esp-hal = { version = "0.21.1", features = ["esp32s3", "log"] }
esp-alloc = { version = "0.5.0", features = ["nightly"] }
esp-hal-embassy = { version = "0.4.0", features = [
    "esp32s3", "log",
    "integrated-timers"
] }
embassy-executor     = { version = "0.6.1", features = [
    "executor-interrupt", "executor-thread",
    "integrated-timers",
    "log", "task-arena-size-16384"
] }
static_cell = { version = "2.1.0", features = ["nightly"] }
...
```

3. I get a runtime panic:

```
====================== PANIC ======================
panicked at /home/being/.cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-hal-0.21.1/src/timer/systimer.rs:949:44:
called `Option::unwrap()` on a `None` value
```
4. [Observation](https://matrix.to/#/!LdaNPfUfvefOLewEIM:matrix.org/$d05kMz-RY8WPH84fD9kH26HroqQxMbg7Y6UA3_lMdks?via=matrix.org&via=tchncs.de&via=envs.net) from @bugadani: Using the other timers instead, works (i.e. no panic in over 1 hour):

```
 let timg0 = TimerGroup::new(peripherals.TIMG0);
 let timer1: AnyTimer = timg0.timer1.into();
 let timg1 = TimerGroup::new(peripherals.TIMG1);
 let timer10: AnyTimer = timg1.timer0.into();
 esp_hal_embassy::init([timer1, timer10]);
```

## Expected behavior

There should be no panic!

## Environment

- Target device: ESP32-S3
- Crate name and version: esp-hal v0.21.1
- `rustc --version`: `rustc 1.82.0-nightly (ffd10cecc 2024-10-25) (1.82.0.1)`
- `espup --version`: `espup 0.11.0`

### LINKED ISSUE #2432: esp-hal-embassy clock initialization with a single SysTimer Alarm panics shortly after
## Bug description

With esp-hal `v0.21.1`, initializing embassy with **a single one** of the SysTimer alarms results in a runtime panic (different than the one in #2431), shortly after `esp_hal_embassy::init(...);`

## To Reproduce

1. With the following program:

```
#[main]
async fn main(spawner: Spawner) -> ! {
    esp_println::logger::init_logger_from_env();
    let peripherals = esp_hal::init(esp_hal::Config::default());

    let systimer = SystemTimer::new(peripherals.SYSTIMER).split::<Target>();
    esp_hal_embassy::init(systimer.alarm0);

    let mut cpu_control = CpuControl::new(peripherals.CPU_CTRL);
    let io = Io::new(peripherals.GPIO, peripherals.IO_MUX);

    // WiFi PHY start
    let timg0 = TimerGroup::new(peripherals.TIMG0);
    let mut rng = Rng::new(peripherals.RNG);
    esp_alloc::heap_allocator!(74 * 1024);
    let seed = ((rng.random() as u64) << 32) | (rng.random() as u64);
    let init = esp_wifi::init(
        esp_wifi::EspWifiInitFor::Wifi,
        timg0.timer0,
        rng,
        peripherals.RADIO_CLK,
    )
    .unwrap();
    let (wifi_interface, controller) =
        esp_wifi::wifi::new_with_mode(&init, peripherals.WIFI, WifiStaDevice).unwrap();
    ...
}
```

2. and the following dependencies in `Cargo.toml`:

```
esp-hal = { version = "0.21.1", features = ["esp32s3", "log"] }
esp-alloc = { version = "0.5.0", features = ["nightly"] }
esp-hal-embassy = { version = "0.4.0", features = [
    "esp32s3", "log",
    "integrated-timers"
] }
embassy-executor     = { version = "0.6.1", features = [
    "executor-interrupt", "executor-thread",
    "integrated-timers",
    "log", "task-arena-size-16384"
] }
static_cell = { version = "2.1.0", features = ["nightly"] }
...
```

3. I get a runtime panic:

```
====================== PANIC ======================
panicked at /home/being/.cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-hal-embassy-0.4.0/src/time_driver.rs:167:30:
index out of bounds: the len is 1 but the index is 1
```

4. [Observation](https://matrix.to/#/!LdaNPfUfvefOLewEIM:matrix.org/$d05kMz-RY8WPH84fD9kH26HroqQxMbg7Y6UA3_lMdks?via=matrix.org&via=tchncs.de&via=envs.net) from @bugadani: Using the other timers instead, works (i.e. no panic in over 1 hour):

```
 let timg0 = TimerGroup::new(peripherals.TIMG0);
 let timer1: AnyTimer = timg0.timer1.into();
 let timg1 = TimerGroup::new(peripherals.TIMG1);
 let timer10: AnyTimer = timg1.timer0.into();
 esp_hal_embassy::init([timer1, timer10]);
```

## Expected behavior

There should be no panic!

## Environment

- Target device: ESP32-S3
- Crate name and version: esp-hal v0.21.1
- `rustc --version`: `rustc 1.82.0-nightly (ffd10cecc 2024-10-25) (1.82.0.1)`
- `espup --version`: `espup 0.11.0`

### PR DESCRIPTION
**Pull request by bugadani**
- Optimize register access
- Clean up duplicate code - this might be enough to prevent the panics seen in #2431
- Improve panic message for #2432
- Ensure consistency when reading the counter.

Closes #2431
Closes #2432

At least in theory, I did not spend time reproducing the race issue. I do not think we can test the race condition easily so I didn't add a test case.

### CODE REVIEW

File: esp-hal/src/timer/systimer.rs [hunk 1]
```diff
@@ -374,10 +367,16 @@ impl<const CHANNEL: u8> SpecificUnit<'_, CHANNEL> {
     }
 }
 
+const CHANNEL_COUNT: usize = 3;
```
Comment (Dominaezzz) [inline esp-hal/src/timer/systimer.rs:370]: 3?

Comment (bugadani) [reply esp-hal/src/timer/systimer.rs]: Thanks - this was a random placeholder that I forgot to fact-check.

File: esp-hal/src/timer/systimer.rs [hunk 2]
```diff
@@ -317,50 +311,49 @@ pub trait Unit {
...
-    ///
-    /// This can be used to read the current value of the timer.
-    fn update(&self) {
-        let systimer = unsafe { &*SYSTIMER::ptr() };
-        systimer
-            .unit_op(self.channel() as _)
-            .modify(|_, w| w.update().set_bit());
-    }
+    /// Reads the current counter value.
+    fn read_count(&self) -> u64 {
```
Comment (Dominaezzz) [inline esp-hal/src/timer/systimer.rs:315]: Any objections moving this synchronization logic into `Alarm` and leaving Unit as the low level API (i.e. update and poll)?

File: esp-hal/src/timer/systimer.rs [hunk 3]
```diff
@@ -317,50 +311,49 @@ pub trait Unit {
...
+
+        // Perf impact:
+        // - ESP32 has no systimer, no impact
+        // - ESP32-S3 and P4 have atomic instructions, no multicore critical section
+        //   should be needed.
+        // - Other chips are single core, the atomic swap chould acquire a single-core
+        //   critical section which should be cheap enough.
+        let flag = self.updating_flag();
+        let channel = self.channel() as usize;
+        let was_updating = flag.swap(true, Ordering::Acquire);
```
Comment (Dominaezzz) [inline esp-hal/src/timer/systimer.rs:334]: I can't believe I'm saying this but a full blown critical section might be more desirable here. I'm concerned an InterruptExecutor setup could cause issues with this implementation.

Comment (Dominaezzz) [reply esp-hal/src/timer/systimer.rs:334]: Oh actually, perhaps we can use one unit per core, that way we can get away with a plain interrupt::free rather than a critical section. 🤔

Comment (bugadani) [reply esp-hal/src/timer/systimer.rs:334]: Prove to me that this is incorrect and I'll happily put a critical section into this function. Right now I feel like I've put enough effort into making this correct, and a critical section is fairly expensive on multi-core just to ensure the invariants we need here.

File: esp-hal/src/timer/systimer.rs (hunk 2 above)
Comment (bugadani) [reply esp-hal/src/timer/systimer.rs:315]: Not much, besides the desire to not expose footgun parts.

File: esp-hal/src/timer/systimer.rs (hunk 3 above)
Comment (Dominaezzz) [reply esp-hal/src/timer/systimer.rs:334]: So let's say we have two tasks, task A (high priority) and task B (low priority).

Let's say task B:
- Sets the atomic
- asks for an update
- gets prempted by task A

Task A also wants the time: 
- checks the atomic
- skips the update
- polls until it gets a count
- does CPU intensive work for 5 seconds
- yields (waits for interrupt I guess) 

Task B now resumes: 
- polls and immediately gets a count (since task A has done the polling)
- task B now has a count that is 5 seconds stale
- task B unsets the atomic

Of course, if there are other tasks with higher priority that prempt task B before it unsets the atomic, they will all get stale (and unchanged) counts until task B resumes.

I also just realised this could result in a dead lock if the higher priority task is blocking until the count increases to a certain amount, i.e. `Delay::new().delay_ms(10)`.

Comment (bugadani) [reply esp-hal/src/timer/systimer.rs:334]: Yaay, good point, thanks. Also the tests fail which I hope is caused by this because I'm pretty baffled right now :)

Comment (bugadani) [reply esp-hal/src/timer/systimer.rs]: I'm thinking we might be able to get away with `interrupt::free` and a counter (to prevent the first core from looping back into updating inappropriately). Instead of the `swap(true)` we'd `fetch_and_add(1)`. The interrupt free context ensures the counter is only ever 0, 1 or 2. The problem I can see is, two cores reading the counter in a loop can mutually prevent each other from updating, which is a weird edge case, one which I'm not sure we have to handle correctly.

Comment (bugadani) [reply esp-hal/src/timer/systimer.rs]: > task B now has a count that is 5 seconds stale

To be quite fair, nothing really prevents this if that blocking interrupt handler is fired. The critical section is released, the interrupt is handled, and the lower priority context still ends up with a 5 seconds stale counter. The deadlock is a much better argument.

Comment (Dominaezzz) [reply esp-hal/src/timer/systimer.rs]: > Anyway I'm not sure we'd actually end up with something faster.

Yeah using interrupt::free only makes sense performance wise if you skip the atomics on the counter/flag.

File: esp-hal/src/timer/systimer.rs (hunk 2 above)
Comment (Dominaezzz) [reply esp-hal/src/timer/systimer.rs:310]: Now that `read_count()` is expensive, do I have a stronger argument? 😄

File: esp-hal/src/timer/systimer.rs (hunk 3 above)
Comment (bugadani) [reply esp-hal/src/timer/systimer.rs]: Why only then? How else would you guarantee consistency on dualcores?

File: esp-hal/src/timer/systimer.rs (hunk 2 above)
Comment (bugadani) [reply esp-hal/src/timer/systimer.rs:307]: How about now, now that it's cheap again? 🙃

Comment (Dominaezzz) [reply esp-hal/src/timer/systimer.rs:307]: Yeah I don't think I have a strong enough case anymore haha

**Review by bjoernQ — APPROVED** [review]
Seems I cannot reproduce the original issue, but the changes look good to me

**Review by JurajSadel — APPROVED** [review]
Thanks!
