### PR TITLE
esp-wifi: fix possible deadlock

### LINKED ISSUE #3008: Potential deadlock on esp32-c3 when using listening sockets on embassy-net
## Bug description

When running an echo-server using 4 sockets over wifi, sometimes my program will freeze up under high load in what appears to be a deadlock.

The last lines of logging appears to come from the function `lock_mutex` inside the file `esp-wifi/src/compat/common.rs`.

## To Reproduce

I have a reproducer here: https://github.com/TethysSvensson/esp32-wifi-deadlock-poc

## Expected behavior

I do not a expect my board to freeze up.

## Environment

```
$ espflash board-info
[2025-01-21T13:42:57Z INFO ] 🚀 A new version of espflash is available: v3.3.0
[2025-01-21T13:42:57Z INFO ] Serial port: '/dev/ttyACM0'
[2025-01-21T13:42:57Z INFO ] Connecting...
[2025-01-21T13:42:57Z INFO ] Using flash stub
Chip type:         esp32c3 (revision v0.4)
Crystal frequency: 40 MHz
Flash size:        4MB
Features:          WiFi, BLE
MAC address:       40:4c:ca:8c:f4:0c
```

I am using `esp-hal` version `0.23.1`. For other versions, see my reproducer.

### PR DESCRIPTION
**Pull request by bjoernQ**
## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [ ] I have updated existing examples or added new ones (if applicable).
- [x] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [x] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [ ] I have added necessary changes to user code to the [Migration Guide](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/MIGRATING-0.21.md).
- [x] My changes are in accordance to the [esp-rs API guidelines](https://github.com/esp-rs/esp-hal/blob/main/documentation/API-GUIDELINES.md)

#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/documentation/CONTRIBUTING.md) and followed its instructions.

#### Description
Fixes #3008 

In case the rx-queue is overrun it was possible the drop-implementation of `EspWifiPacketBuffer` was called with interrupts disabled (which can cause a dead-lock).

#### Testing
See linked issue

### CODE REVIEW

File: esp-wifi/src/wifi/mod.rs [hunk 1]
```diff
@@ -1541,13 +1541,15 @@ unsafe extern "C" fn recv_cb_sta(
             queue.push_back(packet);
             true
         } else {
+            mem::forget(packet);
```
Comment (bugadani) [inline esp-wifi/src/wifi/mod.rs:1544]: Please add a comment that we're not allowed to drop `packet` here, otherwise we'll call `esp_wifi_internal_free_rx_buffer` in a critical section which is apparently NotGood(TM)

Comment (bjoernQ) [reply esp-wifi/src/wifi/mod.rs:1544]: you already added that comment loooong time ago a few lines above

Comment (bjoernQ) [reply esp-wifi/src/wifi/mod.rs:1544]: really long time ago:

image

Comment (bugadani) [reply esp-wifi/src/wifi/mod.rs:1544]: Huh. Okay. What would you say to a different solution, that doesn't involve `forget`? We could return `Ok(()) / Err(packet)`, and dropping that would free the buffer.

Comment (bjoernQ) [reply esp-wifi/src/wifi/mod.rs:1544]: sure that should work and probably looks a little bit better

**Review by bugadani — APPROVED** [review]

**Review by MabezDev — APPROVED** [review]
