### PR TITLE
Fix GPIO interrupts for pins > 31

### LINKED ISSUE #332: GPIO incorrect interrupt status for pins > 32
For pins > 32, the interrupt status-related methods fail. This is because the access methods only return a u32, see https://github.com/esp-rs/esp-hal/blob/fe6ea5321b7a26dc087629aaf9c524ab0ff335cf/esp-hal-common/src/gpio.rs#L277. This should be a u64 at least.

To reproduce, apply this diff and run the S3 gpio_interrupt example. Even though pin 42 fires, its status bit reports it hasn't.
```diff
diff --git a/esp32s3-hal/examples/gpio_interrupt.rs b/esp32s3-hal/examples/gpio_interrupt.rs
index 215829c..42b3fa3 100644
--- a/esp32s3-hal/examples/gpio_interrupt.rs
+++ b/esp32s3-hal/examples/gpio_interrupt.rs
@@ -11,7 +11,7 @@ use core::cell::RefCell;
 use critical_section::Mutex;
 use esp32s3_hal::{
     clock::ClockControl,
-    gpio::{Event, Gpio0, Input, PullDown, IO},
+    gpio::{Event, Gpio42, Input, PullDown, IO},
     interrupt,
     macros::ram,
     peripherals::{self, Peripherals},
@@ -23,7 +23,7 @@ use esp32s3_hal::{
 use esp_backtrace as _;
 use xtensa_lx_rt::entry;
 
-static BUTTON: Mutex<RefCell<Option<Gpio0<Input<PullDown>>>>> = Mutex::new(RefCell::new(None));
+static BUTTON: Mutex<RefCell<Option<Gpio42<Input<PullDown>>>>> = Mutex::new(RefCell::new(None));
 
 #[entry]
 fn main() -> ! {
@@ -43,7 +43,7 @@ fn main() -> ! {
     // Set GPIO15 as an output, and set its state high initially.
     let io = IO::new(peripherals.GPIO, peripherals.IO_MUX);
     let mut led = io.pins.gpio15.into_push_pull_output();
-    let mut button = io.pins.gpio0.into_pull_down_input();
+    let mut button = io.pins.gpio42.into_pull_down_input();
     button.listen(Event::FallingEdge);
 
     critical_section::with(|cs| BUTTON.borrow_ref_mut(cs).replace(button));
@@ -57,6 +57,15 @@ fn main() -> ! {
     let mut delay = Delay::new(&clocks);
 
     loop {
+        critical_section::with(|cs| {
+            let is_set = BUTTON
+                .borrow_ref_mut(cs)
+                .as_mut()
+                .unwrap()
+                .is_pcore_interrupt_set();
+
+            esp_println::println!("Is interrupt bit set for pin? {}", is_set);
+        });
         led.toggle().unwrap();
         delay.delay_ms(500u32);
     }
@@ -70,11 +79,5 @@ fn GPIO() {
         xtensa_lx::interrupt::get_level()
     );
 
-    critical_section::with(|cs| {
-        BUTTON
-            .borrow_ref_mut(cs)
-            .as_mut()
-            .unwrap()
-            .clear_interrupt()
-    });
+    interrupt::disable(esp_hal_common::get_core(), peripherals::Interrupt::GPIO);
 }
```

### PR DESCRIPTION
**Pull request by bjoernQ**
Fixes #332 

Took me a bit too long because I fell into a "generics" rabbit-hole

### CODE REVIEW

File: esp-hal-common/src/gpio.rs [hunk 1]
```diff
@@ -1062,54 +1139,60 @@ where
...
     }
 
-    pub fn into_push_pull_output(self) -> GpioPin<Output<PushPull>, RA, PINTYPE, GPIONUM> {
+    pub fn into_push_pull_output(self) -> GpioPin<Output<PushPull>, RA, IRA, PINTYPE, GPIONUM> {
         self.init_output(GPIO_FUNCTION, false);
         GpioPin {
             _mode: PhantomData,
             _pintype: PhantomData,
             reg_access: self.reg_access,
+            ira: self.ira,
```
Comment (MabezDev) [inline esp-hal-common/src/gpio.rs:1148]: Is the ira field needed? Looks like the usage doesn't require self so it can just be called with `IRA::XXXX`? IRA should probably be a `PhantomData` field, unless I'm missing something?

**Review by MabezDev — CHANGES_REQUESTED** [review]
> Took me a bit too long because I fell into a "generics" rabbit-hole

We've all been there :D.

File: esp-hal-common/src/gpio.rs (hunk 1 above)
Comment (bjoernQ) [reply esp-hal-common/src/gpio.rs:1148]: I think `PhantomData` should be enough - also for `reg_access` ... I assumed it's zero-sized in both cases but anyway probably better to stick to `PhantomData` ... will check

Comment (bjoernQ) [reply esp-hal-common/src/gpio.rs:1148]: ah I see `BankGpioRegisterAccess` trait functions take `&self` but for no reason

**Review by MabezDev — APPROVED** [review]
Thanks for fixing this. LGTM!
