### PR TITLE
Have a way to get the booted partition

### LINKED ISSUE #3918: (esp-bootloader-esp-idf) Find the actual running partition when the boot partition configured in otadata failed to boot
## Motivations

An unused slot needs to be found For OTA updating. The current example calls `Ota::current_slot`, which reads and interprets the `otadata` partition. But if the configured partition contains a broken image, the bootloader normally tries to boot from a different OTA app partition. Boot logs may look like:

> E (86) esp_image: image at 0x120000 has invalid magic byte (nothing flashed here?)
> E (93) boot: OTA app partition slot 1 is not bootable
> I (282) boot: Loaded app from partition at offset 0x40000

In this case, `Ota::current_slot` would still consider slot 1 to be current. The situation is exacerbated by ESP-IDF's bootloader only supporting two OTA slots. Next update slot would be slot 0 at offset 0x40000 with running code. 

## ESP-IDF's Solution

It looks for the running partition by getting the flash address of currently running code and find the partition containing it.

https://github.com/espressif/esp-idf/blob/4e036983a751e4667ade94c8f6f6bf1e7f78eff0/components/app_update/esp_ota_ops.c#L776

The function `spi_flash_cache2phys` makes an appearance in `esp-rom-sys`: https://github.com/esp-rs/esp-hal/blob/5982222a40ef5a2b773ffb608c238ec228132526/esp-rom-sys/ld/esp32c2/rom/esp32c2.rom.ld#L140

### PR DESCRIPTION
**Pull request by bjoernQ**
## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [ ] I have updated existing examples or added new ones (if applicable).
- [ ] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [ ] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [ ] I have added necessary changes to user code to the [Migration Guide](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/MIGRATING-0.21.md).
- [ ] My changes are in accordance to the [esp-rs developer guidelines](https://github.com/esp-rs/esp-hal/blob/main/documentation/DEVELOPER-GUIDELINES.md)

#### Extra:
- [ ] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/documentation/CONTRIBUTING.md) and followed its instructions.

#### Description

Closes #3918

#### Testing

Running the updates example on all targets

### CODE REVIEW

File: esp-bootloader-esp-idf/src/partitions.rs [hunk 1]
```diff
@@ -301,6 +301,45 @@ impl<'a> PartitionTable<'a> {
         }
         Ok(None)
     }
+
+    #[cfg(not(feature = "std"))]
+    /// Get the currently booted partition.
+    pub fn booted_partition(&self) -> Result<Option<PartitionEntry<'a>>, Error> {
+        cfg_if::cfg_if! {
```
Comment (Dominaezzz) [inline esp-bootloader-esp-idf/src/partitions.rs:311]: Mind adding a link to where these magic numbers came from?

**Review by JurajSadel — APPROVED** [review]
Thanks!

File: esp-bootloader-esp-idf/src/partitions.rs [hunk 2]
```diff
@@ -301,6 +301,48 @@ impl<'a> PartitionTable<'a> {
...
+                    ((0x600C5000 as *const u32).read_volatile() & 0xff) << 16
+                };
+            } else if #[cfg(any(feature = "esp32c2", feature = "esp32c3"))] {
+                let paddr = unsafe {
+                    ((0x600c5000 as *const u32).read_volatile() & 0xff) << 16
+                };
+            } else if #[cfg(any(feature = "esp32c6", feature = "esp32h2"))] {
+                let paddr = unsafe {
+                    ((0x60002000 + 0x380) as *mut u32).write_volatile(0);
+                    (((0x60002000 + 0x37c) as *const u32).read_volatile() & 0xff) << 16
```
Comment (bugadani) [inline esp-bootloader-esp-idf/src/partitions.rs:332]: Couldn't we use the PAC for all these?

Comment (bjoernQ) [reply esp-bootloader-esp-idf/src/partitions.rs:332]: We could add those registers ofc - I just assumed it's not worth just for this sole use but we should assess that decision once we have more uses for that - I can create an issue for that if you like

Comment (bugadani) [reply esp-bootloader-esp-idf/src/partitions.rs:332]: It would be great (https://github.com/esp-rs/esp-hal/issues/2748)
