### PR TITLE
Make sure FD SPI works after HD SPI

### LINKED ISSUE #3122: SPI once half-duplex can't be re-used as full-duplex
## Bug description

After a call to `half_duplex_*` any attempt to get back so far by manual register edits, but presumably also by `steal`ing the SPI peripherals and re-creating it seems to fail.

Currently unable to continue testing due to missing hardware.

## To Reproduce

```rust
spibus
    .half_duplex_write(
      mode,
      Command::None,
      Address::_24Bit(addr_spi_mode, mode),
      0u8,
      &(0u32.to_le_bytes()),
    )?;
let spi_config_fast = esp_hal::spi::master::Config::default()
        .with_frequency((23).MHz())
        .with_mode(esp_hal::spi::Mode::_0);
spibus.apply_config(&spi_config_fast);

// Do a SPI transfer here with an expected result; you'll get all 0x00.
```

Attempts to reconfigure registers (without success): https://github.com/i404788/esp-hal/commit/0796e011d19a6566398fa0b4a1e32dbc4c932a88 

## Expected behavior

When using `half_duplex_write` the data modes specified should be configured, when returning to the regular interface (`tranfer`/eh1) full-duplex is used again.

## Environment

- Target device: ESP32-S3
- Crate name and version: `main~52` (0.23.1-dev)

NOTE: split from the end of https://github.com/esp-rs/esp-hal/issues/2863

### PR DESCRIPTION
**Pull request by bjoernQ**
## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [ ] I have updated existing examples or added new ones (if applicable).
- [x] I have used `cargo xtask fmt-packages` command to ensure that all changed code is formatted correctly.
- [x] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md) in the **_proper_** section.
- [ ] I have added necessary changes to user code to the [Migration Guide](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/MIGRATING-0.21.md).
- [x] My changes are in accordance to the [esp-rs API guidelines](https://github.com/esp-rs/esp-hal/blob/main/documentation/API-GUIDELINES.md)

#### Extra:
- [x] I have read the [CONTRIBUTING.md guide](https://github.com/esp-rs/esp-hal/blob/main/documentation/CONTRIBUTING.md) and followed its instructions.

#### Description
Fixes #3122

#### Testing
HIL testing, modified local example

### CODE REVIEW

**Comment by MabezDev** [comment]
I suppose we can't make half duplex function disable itself because transactions don't have to finish before returning, and that makes flushing complicated?

**Comment by bjoernQ** [comment]
> I suppose we can't make half duplex function disable itself because transactions don't have to finish before returning, and that makes flushing complicated?

Yes that's a problem - and we do the same thing (inversed) for half-duplex operations. I'm not sure if three register writes are expensive enough that it's worth to avoid them (and avoiding is probably also not for free)

File: esp-hal/src/spi/master.rs [hunk 1]
```diff
@@ -3379,6 +3401,23 @@ impl Driver {
         future.await;
     }
 
+    fn disable_half_duplex(&self) -> Result<(), Error> {
```
Comment (Dominaezzz) [inline esp-hal/src/spi/master.rs:3404]: I suppose this is just `setup_full_duplex` at the end of the day.
Hopefully this can be unified with `setup_half_duplex` in future.

Comment (bjoernQ) [reply esp-hal/src/spi/master.rs:3404]: sure - probably setup_full_duplex sounds better 👍

**Review by MabezDev — APPROVED** [review]
Thanks, LGTM

**Review by Dominaezzz — APPROVED** [review]
