### PR TITLE
Fix PeripheralRef

### LINKED ISSUE #2661: Evaluate the `Peripheral` and `Peripheral` ref module
For various issues, documentation and soundness issue, for example are we affected by https://github.com/embassy-rs/embassy/pull/2919

### PR DESCRIPTION
**Pull request by bugadani**
This PR applies the soundness fixes from embassy-hal-internal to our copy-pasted implementation, and modifies code where necessary to allow that change.

There are three noteworthy items:
- I've removed Peripheral: Sealed, as it is just in the way. Preventing the users from implementing the trait (e.g. like we do for Flex) doesn't give us much, I believe.
- I've removed a few InterruptConfigurable implementations from timers. I don't think we should implement that trait for peripheral singletons, we should keep it for peripheral drivers only.
- I've changed all methods on peripheral singletons to use `&self`. These are supposed to be singletons, and they shouldn't really have user-facing APIs anyway. `&mut self` wasn't really preventing anything anyway (e.g. we can race on GPIO configuration), but it was in the way of this PR.

Closes #2661 as we now have an identical implementation to embassy, except for a few custom additions where we abuse the pattern a bit.

### CODE REVIEW

**Review by bjoernQ — APPROVED** [review]
Thanks

**Review by SergioGasquez — APPROVED** [review]
LGTM! Thanks

File: esp-hal/src/gpio/mod.rs [hunk 1]
```diff
@@ -2250,37 +2255,36 @@ impl RtcPin for AnyPin {
...
-            RtcPin::rtc_set_config(&mut target, input_enable, mux, func)
+            RtcPin::rtc_set_config(&target, input_enable, mux, func)
         })
     }
 
-    fn rtcio_pad_hold(&mut self, enable: bool) {
-        handle_rtcio!(self, target, {
-            RtcPin::rtcio_pad_hold(&mut target, enable)
-        })
+    #[allow(unused_braces, reason = "False positive")]
```
Comment (SergioGasquez) [inline esp-hal/src/gpio/mod.rs:2264]: Curious, do you remember what braces were failing? The method is very similar to `rtc_set_config` which doesn't seem to complain.

Comment (bugadani) [reply esp-hal/src/gpio/mod.rs:2264]:
```
warning: unnecessary braces around block return value
    --> C:\_Espressif\esp-hal\esp-hal\src\gpio\mod.rs:2265:37
     |
2265 |         handle_rtcio!(self, target, { RtcPin::rtcio_pad_hold(&target, enable) })
     |                                     ^^                                       ^^
     |
     = note: `#[warn(unused_braces)]` on by default
help: remove these braces
     |
2265 -         handle_rtcio!(self, target, { RtcPin::rtcio_pad_hold(&target, enable) })
2265 +         handle_rtcio!(self, target, RtcPin::rtcio_pad_hold(&target, enable))
```

This is some weird interaction between using a macro, and the whole expression being in a single line. If `rtc_set_config` was a bit shorter, it would trigger the same warning.

Comment (bugadani) [reply esp-hal/src/gpio/mod.rs:2264]: https://github.com/rust-lang/rust/issues/88104
