### PR TITLE
RNG workaround for H2-ECO5

### LINKED ISSUE #4698: `bas_peripheral` example is broken on ESP32H2
## Bug description

this ble device can not be scaned
```
ESP-ROM:esp32h2-eco5-20240613
Build:Jun 13 2024
rst:0x15 (USB_UART_HPSYS),boot:0x1f (SPI_FAST_FLASH_BOOT)
Saved PC:0x4080082e
0x4080082e - <esp_hal::gpio::AnyPin as esp_hal::gpio::InputPin>::waker
    at ??:??
SPIWP:0xee
mode:DIO, clock div:2
load:0x408460e0,len:0x1674
load:0x4083cad0,len:0xf08
load:0x4083efd0,len:0x2eec
entry 0x4083cada
I (23) boot: ESP-IDF v5.4.1-426-g3ad36321ea 2nd stage bootloader
I (24) boot: compile time Apr 29 2025 15:13:26
I (25) boot: chip revision: v1.2
I (25) boot: efuse block revision: v0.3
I (28) boot.esp32h2: SPI Speed      : 32MHz
I (32) boot.esp32h2: SPI Mode       : DIO
I (36) boot.esp32h2: SPI Flash Size : 4MB
I (40) boot: Enabling RNG early entropy source...
I (44) boot: Partition Table:
I (47) boot: ## Label            Usage          Type ST Offset   Length
I (53) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (60) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (66) boot:  2 factory          factory app      00 00 00010000 003f0000
I (73) boot: End of partition table
I (76) esp_image: segment 0: paddr=00010020 vaddr=42000020 size=0c198h ( 49560) map
I (98) esp_image: segment 1: paddr=0001c1c0 vaddr=40800000 size=00014h (    20) load
I (100) esp_image: segment 2: paddr=0001c1dc vaddr=4200c1dc size=66dc8h (421320) map
I (227) esp_image: segment 3: paddr=00082fac vaddr=40800014 size=083e4h ( 33764) load
I (242) boot: Loaded app from partition at offset 0x10000
I (242) boot: Disabling RNG early entropy source...
INFO - Our address = Address { kind: AddrKind(1), addr: BdAddr([255, 143, 26, 5, 228, 255]) }
INFO - Starting advertising and GATT service
```

## To Reproduce

1. add default feature ["esp32h2"] to `bas_peripheral/Cargo.toml`
2. add target `riscv32imac-unknown-none-elf` to `bas_peripheral/.cargo/config.toml`
3. `cargo run --release`

## Expected behavior

this device can  be scaned and connected.

## Environment

- Target device: esp32h2 v1.2
- Crate name and version: esp-hal 9c7c809c

### PR DESCRIPTION
**Pull request by bjoernQ**
Definitely not the solution we want to end-up with (will create a separate issue to discuss that) but something that makes things work

Fixes #4698

### CODE REVIEW

File: esp-hal/src/rng/ll.rs [hunk 1]
```diff
@@ -63,7 +63,22 @@ fn read_one(wait_cycles: usize) -> u32 {
...
+
+                cfg_if::cfg_if! {
+                    if #[cfg(not(esp32h2))] {
+                        Some(RNG::regs().data().read().bits())
+                    } else {
+                        // TODO find a better way to do this
+                        //
+                        // On H2-ECO5+ the LPPERI peripherals contains an additional register inserted before the `rng_data` register.
+                        // https://github.com/espressif/esp-idf/commit/4c5e1a03414a6d55be4b42ba071b30ad228414f6#diff-bc8f2eca37e32ee4ba21ac812e4934998e764132a400479c4d091eb6f7e2e444
+                        if crate::efuse::Efuse::major_chip_version() >= 1 && crate::efuse::Efuse::minor_chip_version() >= 2 {
```
Comment (bugadani) [inline esp-hal/src/rng/ll.rs]:
```suggestion
                        if crate::soc::chip_revision_above(102) {
```

This will optimize away the old branch if MIN_CHIP_REVISION is set to a high enough value

File: esp-hal/CHANGELOG.md [hunk 2]
```diff
@@ -892,6 +892,7 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 - Add interrupt related functions to `PeriodicTimer`/`OneShotTimer`, added `ErasedTimer` (#1753)
 - Added blocking `read_bytes` method to `Uart` and `UartRx` (#1784)
 - Add method to expose `InputPin::is_interrupt_set` in `Input<InputPin>` for use in interrupt handlers (#1829)
+- Support ESP32-H2-ECO5 (#4949)
```
Comment (bugadani) [inline esp-hal/CHANGELOG.md]:
```suggestion
- Support ESP32-H2 rev 1.2 (#4949)
```

The ECOs are not public

File: esp-hal/src/rng/ll.rs (hunk 1 above)
Comment (bjoernQ) [reply esp-hal/src/rng/ll.rs]: nice - seems I missed `chip_revision_above` 👍

File: esp-hal/CHANGELOG.md [hunk 3]
```diff
@@ -892,6 +892,7 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 - Add interrupt related functions to `PeriodicTimer`/`OneShotTimer`, added `ErasedTimer` (#1753)
 - Added blocking `read_bytes` method to `Uart` and `UartRx` (#1784)
 - Add method to expose `InputPin::is_interrupt_set` in `Input<InputPin>` for use in interrupt handlers (#1829)
+- Support ESP32-H2 rev 1.2 (#4949)
```
Comment (bugadani) [inline esp-hal/CHANGELOG.md:895]: how did this end up here, under 0.19.0? :D

Comment (bjoernQ) [reply esp-hal/CHANGELOG.md:895]: I guess a rebase gone wrong 🤔
