### PR TITLE
UART: retry reading if not enough data has been read before a timeout

### LINKED ISSUE #4869: wait_for_buffered_data might not wait
`wait_for_buffered_data` can compute `max_threshold` as 0 when the user-configured `rx_fifo_full_threshold` is 0. That then makes `minimum = minimum.min(max_threshold)` become 0, causing the function to skip waiting even when the RX FIFO is empty. This breaks `read_async`’s documented behavior (it may return immediately with 0 bytes) and can lead to a tight loop in `read_exact_async`.

Consider ensuring the effective wait condition never drops below 1 byte when the caller requested `minimum > 0` (e.g., clamp the computed threshold/minimum to at least 1, or handle the "threshold==0" register encoding explicitly).
```suggestion
        let mut max_threshold = max_threshold.min(current_threshold as usize) as u16;
        let mut minimum = minimum.min(Info::RX_FIFO_MAX_THRHD as usize) as u16;

        // Ensure that, when the caller requested waiting for at least one byte, we don't end up
        // with an effective threshold of 0 (which would cause this function to skip waiting).
        if minimum > 0 && max_threshold == 0 {
            max_threshold = 1;
        }

        // The effective threshold must be >= minimum. We ensure this by lowering the minimum number
        // of returnable bytes.
        minimum = minimum.min(max_threshold);
```

_Originally posted by @Copilot in https://github.com/esp-rs/esp-hal/pull/4852#discussion_r2742113010_

### LINKED ISSUE #5436: regression of uart embedded-io-async read behaviour
## Bug description

After every uart read done with `embedded-io-async::Read`, there is one with size 0, which should indicate EOF, even though that's not the case.

These are the logs from the reproducer:
```
[INFO ] res: Ok(11) (uart_loopback src/bin/main.rs:87)
[INFO ] res: Ok(0) (uart_loopback src/bin/main.rs:87)
[INFO ] res: Ok(11) (uart_loopback src/bin/main.rs:87)
[INFO ] res: Ok(0) (uart_loopback src/bin/main.rs:87)
[INFO ] res: Ok(11) (uart_loopback src/bin/main.rs:87)
[INFO ] res: Ok(0) (uart_loopback src/bin/main.rs:87)
```

The bug is present only in `esp-hal 1.1.0`, not in `1.0.0`.

## To Reproduce

Connect together `GPIO10` and `GPIO11`.

https://github.com/tommasoclini/uart_loopback

## Expected behavior

There should be no reads of size 0, which indicate EOF.

## Environment

- Target device: esp32-s3-wroom-1 
- Crate name and version: esp-hal 1.1.0

### PR DESCRIPTION
**Pull request by bugadani**
Fixes #5436
Closes #4869

Two changes are being made:
- `rx_fifo_full_treshold` of 0 is not a sensible value, so it's being disallowed
- `read_async` will now loop while there is no data to return

### CODE REVIEW

**Comment by bugadani** [comment]
That's better :)

File: esp-hal/src/uart/mod.rs [hunk 1]
```diff
@@ -3275,7 +3276,7 @@ impl Info {
     ///
     /// ## Errors
     ///
-    /// [ConfigError::UnsupportedTimeout] if the provided value exceeds
+    /// [`ConfigError::TimeoutTooLong`] if the provided value exceeds
```
Comment (MabezDev) [inline esp-hal/src/uart/mod.rs:3279]: Huh, I thought our doc linting pass would catch this?

**Review by MabezDev — APPROVED** [review]
LGTM, thanks!

File: esp-hal/src/uart/mod.rs (hunk 1 above)
Comment (bugadani) [reply esp-hal/src/uart/mod.rs:3279]: apparently not

Comment (bugadani) [reply esp-hal/src/uart/mod.rs:3279]: Thee are private functions (on a `doc(hidden)` struct), those are not documented
